import { db } from "@/db";
import { listings, reviews } from "@/db/schema";
import { sql } from "drizzle-orm";
import { tierForPrice } from "@/lib/constants";

// Real Kenya photography (Pexels) used across the catalogue.
const px = (id: number, w = 1600, h = 1067, ext = "jpeg") =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.${ext}?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;

const TENTS = [17831034, 18671249, 1001437, 9491326, 18717287, 28157088, 30041430, 17831035];
const WILDLIFE = [18960157, 5306128, 30125343, 5306140, 35717988, 20335122, 19294855, 31055413, 30705107, 20865860];
const KILIMANJARO = [35718707, 19267298, 15994021, 29093739, 5109704, 37808650, 15993988];
const ROOMS = [28148280, 6394651, 6434592, 29000312, 6876834, 14025910, 28148281, 2736384, 14025911, 29006838];
const BEACH = [27742235, 20693413, 20693411, 23234936, 36216421, 10489622, 12497747, 7952876];
const LAKES = [7734639, 33473218, 12573131, 33473215, 20653797, 20653421, 30153995];
const POOLS = [12387911, 20975737, 37790193, 20975726, 20975727, 6129994, 5041953];
const DIANI = [33719857, 27742223, 33629231, 8157590, 1591379, 37476348, 2549084];
const BALCONY = [14025912, 20221437, 13205670, 38960514, 11978834, 27349378, 14917459, 33963776];
const SWAHILI = [33802298, 25254990, 18896097];

const imgs = (...ids: number[]) => ids.map((id) => px(id));

type SeedListing = typeof listings.$inferInsert;

const LISTINGS: SeedListing[] = [
  // ---------------- DIANI BEACH & COAST (individual hosts) ----------------
  {
    title: "Kongo River Mouth Villa",
    slug: "kongo-river-mouth-villa",
    description:
      "Our family beachfront home where the Kongo River meets the sea at Galu — swim in the estuary, ride the rope swing, and watch colobus monkeys in the garden. Entire villa with a private pool; our housekeeper and cook will look after you.",
    propertyType: "beach_villa",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Kongo River",
    hostName: "Asha Mwakio",
    hostSince: 2017,
    hostBio: "Diani local and former kitesurf instructor. I'll point you to the best sunset dhow and hidden reef.",
    superhost: true,
    pricePerNight: 58000,
    cleaningFee: 6000,
    locationName: "Diani Beach (Galu)",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.289000",
    longitude: "39.578000",
    bedrooms: 4,
    beds: 5,
    bathrooms: "4",
    maxGuests: 8,
    amenities: ["Free Wi-Fi", "Private pool", "Ocean view", "Beach access", "Air conditioning", "Kitchen", "Self-check-in", "Breakfast included", "Free parking", "Laundry service", "Workspace", "Security 24/7"],
    highlights: ["On the Kongo River estuary", "Entire home with pool & cook", "Colobus monkeys in the garden"],
    imageUrls: imgs(DIANI[0], BALCONY[0], ROOMS[0], POOLS[2], BALCONY[6], DIANI[2]),
    rating: "4.92",
    reviewsCount: 134,
    featured: true,
  },
  {
    title: "Swahili Beach Studio Apartment",
    slug: "swahili-beach-studio-apartment",
    description:
      "My bright studio apartment a short stroll from Swahili Beach and the golden sands of Galu. Self-catering kitchen, fast Wi-Fi and a shared pool make it perfect for couples and digital nomads on a budget.",
    propertyType: "apartment",
    roomType: "entire",
    priceTier: "budget",
    landmark: "Swahili Beach",
    hostName: "Brian Otieno",
    hostSince: 2020,
    hostBio: "I live upstairs and run a small tour desk — ask me about snorkelling trips to the reef.",
    superhost: false,
    pricePerNight: 8500,
    cleaningFee: 800,
    locationName: "Diani Beach (Galu)",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.278000",
    longitude: "39.585000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Air conditioning", "Kitchen", "Hot showers", "Workspace", "Beach access", "Self-check-in", "Coffee & tea", "Pool", "Security 24/7"],
    highlights: ["Walk to Swahili Beach", "Self-catering & fast Wi-Fi", "Shared pool for guests"],
    imageUrls: imgs(BALCONY[5], ROOMS[6], DIANI[0], BALCONY[2], BEACH[2], ROOMS[7]),
    rating: "4.74",
    reviewsCount: 88,
    featured: false,
  },
  {
    title: "Galu Beach Penthouse",
    slug: "galu-beach-penthouse",
    description:
      "Our top-floor apartment with panoramic sea views over Galu Beach, one of Diani's premier kitesurfing spots. Floor-to-ceiling glass, a private terrace and self-check-in — bring the whole group.",
    propertyType: "apartment",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Galu Beach",
    hostName: "Hannah Schmidt",
    hostSince: 2019,
    hostBio: "Kitesurf addict. I'll set you up with gear rentals and lessons just down the beach.",
    superhost: true,
    pricePerNight: 46000,
    cleaningFee: 4500,
    locationName: "Diani Beach (Galu)",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.281500",
    longitude: "39.582500",
    bedrooms: 2,
    beds: 2,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Ocean view", "Beach access", "Air conditioning", "Kitchen", "Rooftop terrace", "Self-check-in", "Pool", "Free parking", "Laundry service", "Workspace", "Security 24/7"],
    highlights: ["Panoramic Galu sea views", "Private rooftop terrace", "Kitesurf & snorkel on tap"],
    imageUrls: imgs(BALCONY[1], DIANI[0], ROOMS[2], POOLS[0], BALCONY[7], DIANI[5]),
    rating: "4.86",
    reviewsCount: 97,
    featured: true,
  },
  {
    title: "Diani Reef Road Apartment",
    slug: "diani-reef-road-apartment",
    description:
      "My simple, spotless one-bedroom apartment on Diani Beach Road — minutes from the sand, supermarkets and matatus to Ukunda. The best-value base in central Diani for solo travellers and backpackers.",
    propertyType: "apartment",
    roomType: "entire",
    priceTier: "budget",
    landmark: "Diani Beach Road",
    hostName: "Linet Akinyi",
    hostSince: 2021,
    hostBio: "I manage several budget flats in Diani and love helping first-time visitors find their feet.",
    superhost: false,
    pricePerNight: 7500,
    cleaningFee: 700,
    locationName: "Diani Beach",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.265000",
    longitude: "39.587000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Air conditioning", "Kitchen", "Hot showers", "Workspace", "Self-check-in", "Free parking", "Coffee & tea", "Security 24/7", "Beach access"],
    highlights: ["Central Diani on a budget", "Walk to the beach & shops", "Self-check-in"],
    imageUrls: imgs(ROOMS[6], BALCONY[5], DIANI[3], BEACH[0], ROOMS[7], BALCONY[2]),
    rating: "4.62",
    reviewsCount: 73,
    featured: false,
  },
  {
    title: "Tiwi Beach Banda",
    slug: "tiwi-beach-banda",
    description:
      "Our family's thatch banda on the calm, uncrowded sands of Tiwi Beach just north of Diani. Rock pools, gentle tides and beachside hammocks — the coast's most affordable slice of paradise.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "budget",
    landmark: "Tiwi Beach",
    hostName: "Fatuma Hassan",
    hostSince: 2018,
    hostBio: "My family has hosted at Tiwi for years. Fresh fish dinner is on me if the catch is good!",
    superhost: true,
    pricePerNight: 6500,
    cleaningFee: 600,
    locationName: "Tiwi Beach",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.225000",
    longitude: "39.570000",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 3,
    amenities: ["Beach access", "Ocean view", "Kitchen", "Hot showers", "Hammock", "Mosquito nets", "Free parking", "Coffee & tea", "Family friendly", "Bonfire pit"],
    highlights: ["Quiet Tiwi Beach front", "Tidal rock pools", "Fresh catch dinners"],
    imageUrls: imgs(SWAHILI[2], DIANI[0], TENTS[7], BEACH[6], ROOMS[5], DIANI[5]),
    rating: "4.7",
    reviewsCount: 61,
    featured: false,
  },
  {
    title: "Diani Sands Villa",
    slug: "diani-sands-villa",
    description:
      "Our contemporary five-bedroom home in the heart of Diani, with an infinity pool that seems to spill into the ocean. I host with a chef and butler — the ultimate group getaway a stone's throw from the beach bars.",
    propertyType: "beach_villa",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Diani Beach",
    hostName: "Wanjiku Mathenge",
    hostSince: 2016,
    hostBio: "Interior designer and host. I obsess over the details so your group can simply relax.",
    superhost: true,
    pricePerNight: 68000,
    cleaningFee: 7000,
    locationName: "Diani Beach",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.270000",
    longitude: "39.589000",
    bedrooms: 5,
    beds: 6,
    bathrooms: "5",
    maxGuests: 10,
    amenities: ["Free Wi-Fi", "Infinity pool", "Ocean view", "Beach access", "Kitchen", "Air conditioning", "Self-check-in", "Breakfast included", "Free parking", "Laundry service", "Workspace", "Security 24/7"],
    highlights: ["Infinity pool to the ocean", "Chef & butler on call", "Sleeps up to ten"],
    imageUrls: imgs(DIANI[1], ROOMS[0], POOLS[2], BALCONY[0], DIANI[2], ROOMS[8]),
    rating: "4.9",
    reviewsCount: 112,
    featured: true,
  },
  {
    title: "Shimba Hills Forest Banda",
    slug: "shimba-hills-forest-banda",
    description:
      "Our off-grid forest banda inside Shimba Hills National Reserve — the closest rainforest to Diani, home to sable antelope and elephants. Cool mountain air, guided walks to Sheldrick Falls and a true escape.",
    propertyType: "eco_camp",
    roomType: "entire",
    priceTier: "budget",
    landmark: "Shimba Hills NR",
    hostName: "David Mwangi",
    hostSince: 2019,
    hostBio: "Reserve guide for fifteen years. I'll lead you to Sheldrick Falls and the sable viewing platform.",
    superhost: false,
    pricePerNight: 12000,
    cleaningFee: 1200,
    locationName: "Shimba Hills National Reserve",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.250000",
    longitude: "39.410000",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 3,
    amenities: ["Solar power", "Eco-friendly", "Mosquito nets", "Hot showers", "Nature walks", "Wildlife viewing", "Bird watching", "Coffee & tea", "Bonfire pit", "Free parking"],
    highlights: ["Inside Shimba Hills reserve", "Walks to Sheldrick Falls", "Rare sable antelope"],
    imageUrls: imgs(TENTS[6], DIANI[0], ROOMS[6], WILDLIFE[3], BEACH[6], TENTS[7]),
    rating: "4.78",
    reviewsCount: 54,
    featured: false,
  },
  {
    title: "Chale Island Beach House",
    slug: "chale-island-beach-house",
    description:
      "Our private beach house on a tiny sand-fringed forest island south of Galu, reachable only by boat. Mangrove boardwalks, a plunge pool and hammocks under palms make Chale the most romantic hideaway on the South Coast.",
    propertyType: "beach_villa",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Chale Island",
    hostName: "Yusuf Ali",
    hostSince: 2015,
    hostBio: "I manage the island's boat transfers. Watch for dolphins on the crossing!",
    superhost: true,
    pricePerNight: 62000,
    cleaningFee: 5000,
    locationName: "Chale Island",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.350000",
    longitude: "39.560000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Ocean view", "Beach access", "Private pool", "Kitchen", "Air conditioning", "Breakfast included", "Self-check-in", "Snorkelling (extra)", "Security 24/7", "Coffee & tea", "Free parking"],
    highlights: ["Private boat-only island", "Mangrove forest boardwalks", "Plunge pool under the palms"],
    imageUrls: imgs(DIANI[1], POOLS[0], BALCONY[6], DIANI[2], ROOMS[1], BEACH[4]),
    rating: "4.89",
    reviewsCount: 80,
    featured: false,
  },
  {
    title: "Ukunda Town Guesthouse",
    slug: "ukunda-town-guesthouse",
    description:
      "A private room in our friendly family home in Ukunda — the gateway town to Diani — with easy matatu and boda links to the beach. Clean, cool and unbeatable value for budget travellers in transit.",
    propertyType: "guesthouse",
    roomType: "private",
    priceTier: "budget",
    landmark: "Ukunda Town",
    hostName: "Omar Farah",
    hostSince: 2020,
    hostBio: "Ukunda born and bred. I'll arrange your airport taxi and a trustworthy boda to the beach.",
    superhost: false,
    pricePerNight: 5500,
    cleaningFee: 500,
    locationName: "Ukunda",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.282000",
    longitude: "39.562000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Air conditioning", "Hot showers", "Coffee & tea", "Airport transfers", "Security 24/7", "Laundry service", "Free parking"],
    highlights: ["Gateway to Diani on a budget", "Private room in our home", "Easy matatu & boda links"],
    imageUrls: imgs(SWAHILI[1], ROOMS[6], BALCONY[5], BEACH[0], ROOMS[7], DIANI[5]),
    rating: "4.55",
    reviewsCount: 49,
    featured: false,
  },
  {
    title: "Diani Beachfront Penthouse",
    slug: "diani-beachfront-penthouse",
    description:
      "Our sleek two-bedroom apartment right on Diani's main beach, with a wraparound balcony and resort-style pool. Steps from beach bars and dive shops — the sweet spot of comfort and location.",
    propertyType: "apartment",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Diani Beach",
    hostName: "Chloe Martin",
    hostSince: 2018,
    hostBio: "Dive master and host. I'll book your PADI refresher and a sundowner spot at the beach club.",
    superhost: true,
    pricePerNight: 28000,
    cleaningFee: 2500,
    locationName: "Diani Beach",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.268000",
    longitude: "39.585000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Ocean view", "Beach access", "Pool", "Air conditioning", "Kitchen", "Self-check-in", "Free parking", "Security 24/7", "Diving (extra)", "Laundry service", "Workspace"],
    highlights: ["On Diani's main beach", "Wraparound balcony", "Steps from bars & dive shops"],
    imageUrls: imgs(BALCONY[3], ROOMS[2], DIANI[0], POOLS[0], BALCONY[7], DIANI[5]),
    rating: "4.8",
    reviewsCount: 76,
    featured: false,
  },
  {
    title: "Galu Kitesurf Cottage",
    slug: "galu-kitesurf-cottage",
    description:
      "Our breezy two-bedroom cottage a barefoot walk from Galu's kitesurf beach. A covered veranda, outdoor shower for sandy feet and board storage make it a favourite with riders and beach lovers.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Galu Beach",
    hostName: "Amani Otieno",
    hostSince: 2019,
    hostBio: "Kitesurf instructor by day. Board and gear storage is on the house for my guests.",
    superhost: false,
    pricePerNight: 24000,
    cleaningFee: 2200,
    locationName: "Diani Beach (Galu)",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.283000",
    longitude: "39.584000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1.5",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Beach access", "Air conditioning", "Kitchen", "Hot showers", "Self-check-in", "Free parking", "Coffee & tea", "Family friendly", "Security 24/7"],
    highlights: ["Walk to Galu kitesurf beach", "Board & gear storage", "Outdoor sandy-feet shower"],
    imageUrls: imgs(DIANI[1], ROOMS[8], BALCONY[0], BEACH[2], ROOMS[5], DIANI[3]),
    rating: "4.76",
    reviewsCount: 58,
    featured: false,
  },
  {
    title: "Msambweni Sea Cottage",
    slug: "msambweni-sea-cottage",
    description:
      "Our quiet coastal cottage on the sleepy shore of Msambweni, south of Diani. A private garden, sea breeze and a rooftop sundowner spot — perfect for travellers who want the coast without the crowds.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Msambweni",
    hostName: "Njeri Kamau",
    hostSince: 2018,
    hostBio: "I escape Nairobi weekends here. The local fish market is the best on the South Coast.",
    superhost: true,
    pricePerNight: 19000,
    cleaningFee: 1800,
    locationName: "Msambweni",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.470000",
    longitude: "39.450000",
    bedrooms: 2,
    beds: 3,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Ocean view", "Beach access", "Kitchen", "Air conditioning", "Garden", "Hot showers", "Self-check-in", "Free parking", "Coffee & tea", "Family friendly", "Rooftop terrace"],
    highlights: ["Quiet Msambweni shore", "Private garden & rooftop", "Local fish market nearby"],
    imageUrls: imgs(BEACH[4], ROOMS[0], DIANI[3], BALCONY[2], ROOMS[5], BEACH[1]),
    rating: "4.77",
    reviewsCount: 42,
    featured: false,
  },

  // ---------------- WATAMU / MALINDI / LAMU ----------------
  {
    title: "Watamu Bay Beach Villa",
    slug: "watamu-bay-beach-villa",
    description:
      "Our barefoot-luxury villa on Watamu's protected marine park, with a private pool, dhow terrace and a cook on call. Turtle nesting season turns the moonlit beach into something unforgettable.",
    propertyType: "beach_villa",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Watamu Marine Park",
    hostName: "Chloe Martin",
    hostSince: 2018,
    hostBio: "Marine biologist turned host. I'll guide your snorkel over the coral gardens myself.",
    superhost: false,
    pricePerNight: 34000,
    cleaningFee: 4000,
    locationName: "Watamu Marine National Park",
    region: "Coast",
    county: "Kilifi",
    latitude: "-3.352000",
    longitude: "40.102000",
    bedrooms: 2,
    beds: 3,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Ocean view", "Private pool", "Beach access", "Kitchen", "Air conditioning", "Self-check-in", "Free parking", "Family friendly", "Snorkelling (extra)", "Coffee & tea", "Security 24/7"],
    highlights: ["Marine-park beachfront", "Private pool & cook", "Turtle-nesting season"],
    imageUrls: imgs(BEACH[1], ROOMS[0], POOLS[2], BEACH[5], ROOMS[8], BEACH[3]),
    rating: "4.9",
    reviewsCount: 117,
    featured: false,
  },
  {
    title: "Malindi Reef Apartment",
    slug: "malindi-reef-apartment",
    description:
      "Our breezy apartment above Malindi's coral gardens, with a shared beachfront pool and a dive centre next door. Self-check-in and a full kitchen — Vasco da Gama's pillar stands at the end of the bay.",
    propertyType: "apartment",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Vasco da Gama Point",
    hostName: "Marco Rossi",
    hostSince: 2015,
    hostBio: "Dive instructor and host. I'll have fresh catch grilled and your tank filled by sundown.",
    superhost: false,
    pricePerNight: 19500,
    cleaningFee: 2000,
    locationName: "Malindi",
    region: "Coast",
    county: "Kilifi",
    latitude: "-3.480000",
    longitude: "40.120000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 3,
    amenities: ["Free Wi-Fi", "Ocean view", "Pool", "Beach access", "Kitchen", "Air conditioning", "Self-check-in", "Free parking", "Family friendly", "Diving (extra)", "Security 24/7", "Coffee & tea"],
    highlights: ["Above the coral gardens", "Shared beachfront pool", "On-site dive centre"],
    imageUrls: imgs(POOLS[0], BEACH[5], ROOMS[3], BEACH[1], POOLS[6], ROOMS[1]),
    rating: "4.72",
    reviewsCount: 141,
    featured: false,
  },
  {
    title: "Lamu Shela Guesthouse",
    slug: "lamu-shela-guesthouse",
    description:
      "A private room in our whitewashed Swahili home in the dunes of Shela village, Lamu — carved doors, rooftop stars and the call of the ocean. The most authentic, affordable way to experience the old Swahili coast.",
    propertyType: "guesthouse",
    roomType: "private",
    priceTier: "budget",
    landmark: "Shela Beach",
    hostName: "Marco Rossi",
    hostSince: 2018,
    hostBio: "I sail a dhow most mornings. Join me for a sunset sail to Manda Toto.",
    superhost: false,
    pricePerNight: 6000,
    cleaningFee: 500,
    locationName: "Lamu (Shela)",
    region: "Coast",
    county: "Lamu",
    latitude: "-2.250000",
    longitude: "40.910000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Rooftop terrace", "Breakfast included", "Air conditioning", "Hot showers", "Coffee & tea", "Dhow trips (extra)", "Cultural visits", "Security 24/7", "Beach access"],
    highlights: ["Private room in Shela village", "Rooftop dhow sunsets", "Carved-door charm"],
    imageUrls: imgs(SWAHILI[0], ROOMS[1], BEACH[6], ROOMS[5], SWAHILI[2], BEACH[7]),
    rating: "4.72",
    reviewsCount: 66,
    featured: false,
  },
  {
    title: "Lamu Stone Town Apartment",
    slug: "lamu-stone-town-apartment",
    description:
      "Our self-catering apartment in the winding lanes of Lamu Old Town, steps from the waterfront and the dhow harbor. Cool stone walls, a rooftop and total immersion in a UNESCO-listed Swahili town.",
    propertyType: "apartment",
    roomType: "entire",
    priceTier: "budget",
    landmark: "Lamu Old Town",
    hostName: "Yusuf Ali",
    hostSince: 2017,
    hostBio: "My family has traded on this waterfront for generations. I'll book your dhow sunset sail.",
    superhost: true,
    pricePerNight: 7800,
    cleaningFee: 700,
    locationName: "Lamu Island",
    region: "Coast",
    county: "Lamu",
    latitude: "-2.269000",
    longitude: "40.905000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Rooftop terrace", "Kitchen", "Air conditioning", "Hot showers", "Self-check-in", "Coffee & tea", "Cultural visits", "Dhow trips (extra)", "Security 24/7"],
    highlights: ["In UNESCO Lamu Old Town", "Self-catering rooftop flat", "Steps from the dhow harbor"],
    imageUrls: imgs(SWAHILI[1], ROOMS[2], BEACH[7], ROOMS[1], SWAHILI[0], ROOMS[5]),
    rating: "4.8",
    reviewsCount: 71,
    featured: false,
  },

  // ---------------- MAASAI MARA ----------------
  {
    title: "Mara River Tented Camp",
    slug: "mara-river-tented-camp",
    description:
      "My intimate 6-tent camp overlooking a bend of the Mara River, front-row to the wildebeest crossings. Days unfold on private game drives with Maasai guides; nights end with sundowners and dinner under the stars.",
    propertyType: "tented_camp",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Mara River",
    hostName: "Joseph Sironka",
    hostSince: 2014,
    hostBio: "Third-generation Maasai guide turned host. I've led safaris across the Mara for over a decade.",
    superhost: true,
    pricePerNight: 38500,
    cleaningFee: 4000,
    locationName: "Maasai Mara National Reserve",
    region: "Maasai Mara",
    county: "Narok",
    latitude: "-1.521000",
    longitude: "35.098500",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1.5",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Game drives included", "Breakfast included", "Sundowner cocktails", "Star-bed sleeping", "Mosquito nets", "Hot showers", "Solar power", "Eco-friendly", "Airport transfers", "Laundry service"],
    highlights: ["Front-row to the Great Migration", "Star beds under open skies", "Private Maasai-guided drives"],
    imageUrls: imgs(TENTS[0], TENTS[4], WILDLIFE[2], ROOMS[5], POOLS[2], TENTS[7]),
    rating: "4.95",
    reviewsCount: 214,
    featured: true,
  },
  {
    title: "Naboisho Bush Home",
    slug: "naboisho-bush-home",
    description:
      "Our family bush home on a private conservancy bordering the reserve, with a plunge pool that melts into the golden plains. Big Five territory begins at the fence — guests regularly spot lion and cheetah from the deck.",
    propertyType: "bush_villa",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Naboisho Conservancy",
    hostName: "Amara Ndegwa",
    hostSince: 2011,
    hostBio: "Hospitality is in my blood — our family has welcomed travellers to the Mara for three generations.",
    superhost: true,
    pricePerNight: 52000,
    cleaningFee: 6000,
    locationName: "Mara Naboisho Conservancy",
    region: "Maasai Mara",
    county: "Narok",
    latitude: "-1.430000",
    longitude: "35.160000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Private pool", "Game drives included", "Breakfast included", "Kitchen", "Air conditioning", "Self-check-in", "Wildlife viewing", "Cultural visits", "Airport transfers", "Security 24/7", "Laundry service"],
    highlights: ["Plunge pool over the plains", "Big Five right outside", "Walks & night drives allowed"],
    imageUrls: imgs(POOLS[2], ROOMS[1], WILDLIFE[4], KILIMANJARO[0], TENTS[7], POOLS[4]),
    rating: "4.91",
    reviewsCount: 308,
    featured: true,
  },
  {
    title: "Acacia Ridge Bush Villa",
    slug: "acacia-ridge-bush-villa",
    description:
      "Our two-bedroom home perched on a ridge of umbrella acacias, built for families who want the bush to themselves. Floor-to-ceiling glass frames the savanna while our guide tailors every day to your group.",
    propertyType: "bush_villa",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Olare Motorogi Conservancy",
    hostName: "Wanjiku Mathenge",
    hostSince: 2017,
    hostBio: "I split my time between Nairobi and the Mara, designing stays that feel like a home in the wild.",
    superhost: false,
    pricePerNight: 78000,
    cleaningFee: 8000,
    locationName: "Olare Motorogi Conservancy",
    region: "Maasai Mara",
    county: "Narok",
    latitude: "-1.392200",
    longitude: "35.043300",
    bedrooms: 2,
    beds: 3,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Private pool", "Game drives included", "Breakfast included", "Kitchen", "Air conditioning", "Self-check-in", "Bush breakfast", "Family friendly", "Airport transfers", "Laundry service", "Workspace"],
    highlights: ["Whole-home privacy", "Private guide on call", "Sleeps a family of four"],
    imageUrls: imgs(ROOMS[4], TENTS[7], WILDLIFE[8], POOLS[2], ROOMS[8], KILIMANJARO[1]),
    rating: "4.97",
    reviewsCount: 142,
    featured: false,
  },
  {
    title: "Nyati Eco Camp",
    slug: "nyati-eco-camp",
    description:
      "My off-grid, solar-powered camp that proves luxury and sustainability belong together. Composting suites, canvas walls and a campfire kitchen keep you close to the wild while treading lightly on it.",
    propertyType: "eco_camp",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Mara Triangle",
    hostName: "David Mwangi",
    hostSince: 2019,
    hostBio: "Conservation biologist turned host. Every shilling here supports community wildlife patrols.",
    superhost: true,
    pricePerNight: 22500,
    cleaningFee: 2500,
    locationName: "Mara Triangle",
    region: "Maasai Mara",
    county: "Narok",
    latitude: "-1.404500",
    longitude: "35.009800",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Game drives included", "Solar power", "Eco-friendly", "Mosquito nets", "Hot showers", "Bush breakfast", "Bonfire pit", "Bird watching", "Nature walks", "Coffee & tea"],
    highlights: ["100% solar & off-grid", "Community-conservation funded", "Guided nature walks"],
    imageUrls: imgs(TENTS[2], TENTS[5], WILDLIFE[1], POOLS[6], ROOMS[6], KILIMANJARO[4]),
    rating: "4.88",
    reviewsCount: 96,
    featured: false,
  },
  {
    title: "Talek Backpacker Camp",
    slug: "talek-backpacker-camp",
    description:
      "My friendly overland camp near Talek Gate — the most affordable way into the Maasai Mara. A private bed in a shared dome tent, hot showers and a lively communal fire; budget game-drive packages available.",
    propertyType: "tented_camp",
    roomType: "private",
    priceTier: "budget",
    landmark: "Talek Gate",
    hostName: "Joseph Sironka",
    hostSince: 2019,
    hostBio: "Backpacker at heart. I run shared game drives so solo travellers can split the cost.",
    superhost: false,
    pricePerNight: 7000,
    cleaningFee: 500,
    locationName: "Maasai Mara National Reserve",
    region: "Maasai Mara",
    county: "Narok",
    latitude: "-1.500000",
    longitude: "35.080000",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Game drives (extra)", "Mosquito nets", "Hot showers", "Bonfire pit", "Coffee & tea", "Solar power", "Eco-friendly", "Laundry service", "Free parking"],
    highlights: ["Cheapest Big Five access", "Shared game-drive packages", "Social backpacker vibe"],
    imageUrls: imgs(TENTS[6], WILDLIFE[1], ROOMS[6], TENTS[7], WILDLIFE[8], KILIMANJARO[4]),
    rating: "4.6",
    reviewsCount: 142,
    featured: false,
  },

  // ---------------- AMBOSELI ----------------
  {
    title: "Kilimanjaro View Bush Cottage",
    slug: "kilimanjaro-view-bush-cottage",
    description:
      "Our stone cottage beside a permanent elephant highway, where you wake to Kilimanjaro floating pink above the plains. A self-catering base with a view deck and a resident guide for park drives.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Amboseli NP",
    hostName: "Grace Sironka",
    hostSince: 2013,
    hostBio: "Born in the shadow of Kili. I'll point out every elephant family I've known for years.",
    superhost: true,
    pricePerNight: 26000,
    cleaningFee: 4500,
    locationName: "Amboseli National Park",
    region: "Amboseli",
    county: "Kajiado",
    latitude: "-2.641000",
    longitude: "37.223000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1.5",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Kilimanjaro view", "Game drives included", "Kitchen", "Air conditioning", "Hot showers", "Self-check-in", "Wildlife viewing", "Cultural visits", "Coffee & tea", "Laundry service", "Free parking"],
    highlights: ["Unbeatable Kilimanjaro sunrise", "Elephant herds at your gate", "Maasai village visit"],
    imageUrls: imgs(KILIMANJARO[2], KILIMANJARO[0], ROOMS[1], POOLS[1], WILDLIFE[5], TENTS[7]),
    rating: "4.9",
    reviewsCount: 187,
    featured: false,
  },
  {
    title: "Chyulu Tented Retreat",
    slug: "chyulu-tented-retreat",
    description:
      "My elevated canvas suite on the green foothills of the Chyulu Hills, trading dust for cloud forest. Horseback rides to lava caves, bush dinners and the clearest star fields you've ever seen.",
    propertyType: "tented_camp",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Chyulu Hills",
    hostName: "Tom Kiprotich",
    hostSince: 2018,
    hostBio: "Former horse safari guide. I'll match you to the perfect mount for the hills.",
    superhost: false,
    pricePerNight: 28500,
    cleaningFee: 3000,
    locationName: "Chyulu Hills",
    region: "Amboseli",
    county: "Kajiado",
    latitude: "-2.689000",
    longitude: "37.251000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Game drives included", "Breakfast included", "Sundowner cocktails", "Star-bed sleeping", "Mosquito nets", "Hot showers", "Solar power", "Eco-friendly", "Nature walks", "Coffee & tea"],
    highlights: ["Horseback safaris", "Lava-cave expeditions", "Stargazing platforms"],
    imageUrls: imgs(TENTS[3], KILIMANJARO[3], ROOMS[5], WILDLIFE[6], POOLS[2], TENTS[6]),
    rating: "4.84",
    reviewsCount: 64,
    featured: false,
  },

  // ---------------- LAIKIPIA ----------------
  {
    title: "Ol Pejeta Bush Villa",
    slug: "ol-pejeta-bush-villa",
    description:
      "Our home on the largest black rhino sanctuary in East Africa, among the last northern white rhinos on Earth. A private waterhole keeps wildlife in view from dawn to last light.",
    propertyType: "bush_villa",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Ol Pejeta Conservancy",
    hostName: "Linet Akinyi",
    hostSince: 2016,
    hostBio: "Wildlife vet turned host. I can arrange behind-the-scenes visits to the rhino enclosure.",
    superhost: true,
    pricePerNight: 68000,
    cleaningFee: 7000,
    locationName: "Ol Pejeta Conservancy",
    region: "Laikipia",
    county: "Laikipia",
    latitude: "0.021000",
    longitude: "36.949000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Private pool", "Game drives included", "Kitchen", "Air conditioning", "Self-check-in", "Wildlife viewing", "Conservation visits", "Airport transfers", "Laundry service", "Security 24/7", "Coffee & tea"],
    highlights: ["Rhino sanctuary on-site", "Private waterhole view", "Conservation experiences"],
    imageUrls: imgs(ROOMS[0], KILIMANJARO[1], POOLS[2], WILDLIFE[5], ROOMS[8], TENTS[7]),
    rating: "4.93",
    reviewsCount: 158,
    featured: true,
  },
  {
    title: "Lewa Wilderness Eco Camp",
    slug: "lewa-wilderness-eco-camp",
    description:
      "Our camp of canvas-and-thatch suites on a ridge above the Northern Frontier, in a UNESCO-listed haven for Grevy's zebra and rhino. Camel walks and community visits round out the days.",
    propertyType: "eco_camp",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Lewa Wildlife Conservancy",
    hostName: "Kofi Mensah",
    hostSince: 2015,
    hostBio: "I run our women's beadwork cooperative between safaris — ask me about it!",
    superhost: true,
    pricePerNight: 36000,
    cleaningFee: 3500,
    locationName: "Lewa Wildlife Conservancy",
    region: "Laikipia",
    county: "Meru",
    latitude: "0.213000",
    longitude: "37.324000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Game drives included", "Breakfast included", "Solar power", "Eco-friendly", "Hot showers", "Nature walks", "Cultural visits", "Bird watching", "Coffee & tea", "Laundry service"],
    highlights: ["UNESCO World Heritage site", "Grevy's zebra & rhino stronghold", "Camel-backed safaris"],
    imageUrls: imgs(TENTS[6], WILDLIFE[3], ROOMS[6], POOLS[2], KILIMANJARO[4], LAKES[3]),
    rating: "4.89",
    reviewsCount: 110,
    featured: false,
  },
  {
    title: "Borana Farm Stay",
    slug: "borana-farm-stay",
    description:
      "Stay on our working cattle and rhino ranch, blending farm-to-fork dining with frontier comfort. Mountain-bike the savanna, ride with the anti-poaching team, or simply soak in the valley views from the farmhouse.",
    propertyType: "farm_stay",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Borana Conservancy",
    hostName: "Marco Rossi",
    hostSince: 2012,
    hostBio: "I came to climb Mt Kenya and never left. The ranch kitchen is the secret to my happy guests.",
    superhost: false,
    pricePerNight: 42000,
    cleaningFee: 6000,
    locationName: "Borana Conservancy",
    region: "Laikipia",
    county: "Laikipia",
    latitude: "0.085000",
    longitude: "36.982000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1.5",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Private pool", "Game drives included", "Breakfast included", "Kitchen", "Air conditioning", "Self-check-in", "Farm-to-table", "Nature walks", "Mountain biking", "Laundry service", "Coffee & tea"],
    highlights: ["Working ranch & rhino reserve", "Farm-to-table dining", "Mountain-bike safaris"],
    imageUrls: imgs(POOLS[4], ROOMS[3], WILDLIFE[6], KILIMANJARO[0], TENTS[1], ROOMS[5]),
    rating: "4.86",
    reviewsCount: 73,
    featured: false,
  },

  // ---------------- RIFT VALLEY LAKES ----------------
  {
    title: "Lake Naivasha Crescent Cottage",
    slug: "lake-naivasha-crescent-cottage",
    description:
      "Our lakeside cottage on the shore of a freshwater Rift Valley lake, where hippos graze the lawn by night and fish eagles call by day. Boat to Crescent Island and walk among giraffe and zebra.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Lake Naivasha",
    hostName: "Njeri Kamau",
    hostSince: 2016,
    hostBio: "I grew up boating this lake. The hippo clock is more reliable than my watch!",
    superhost: true,
    pricePerNight: 18500,
    cleaningFee: 2000,
    locationName: "Lake Naivasha",
    region: "Rift Valley Lakes",
    county: "Nakuru",
    latitude: "-0.728000",
    longitude: "36.445000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1.5",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Lake view", "Garden", "Kitchen", "Hot showers", "Self-check-in", "Bird watching", "Boat trips (extra)", "Free parking", "Coffee & tea", "Family friendly", "Security 24/7"],
    highlights: ["Lawn visited by hippos", "Boat to Crescent Island", "Walk with giraffe & zebra"],
    imageUrls: imgs(ROOMS[8], LAKES[2], POOLS[0], LAKES[3], ROOMS[5], TENTS[7]),
    rating: "4.79",
    reviewsCount: 132,
    featured: false,
  },
  {
    title: "Flamingo Shore Eco Camp",
    slug: "flamingo-shore-eco-camp",
    description:
      "My camp perched above the soda-ash shallows of a Rift Valley lake, fronting a shifting pink ribbon of lesser flamingos. Rhino, leopard and lion roam the park a short drive away.",
    propertyType: "eco_camp",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Lake Nakuru",
    hostName: "Brian Otieno",
    hostSince: 2019,
    hostBio: "Photographer first, host second. I'll get you to the flamingo shoreline at golden hour.",
    superhost: false,
    pricePerNight: 21000,
    cleaningFee: 2000,
    locationName: "Lake Nakuru National Park",
    region: "Rift Valley Lakes",
    county: "Nakuru",
    latitude: "-0.352000",
    longitude: "36.051000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Lake view", "Game drives included", "Breakfast included", "Solar power", "Eco-friendly", "Mosquito nets", "Hot showers", "Bird watching", "Wildlife viewing", "Coffee & tea"],
    highlights: ["Million-strong flamingo flocks", "Rhino & leopard country", "Golden-hour photography"],
    imageUrls: imgs(LAKES[0], LAKES[6], TENTS[2], ROOMS[6], LAKES[5], WILDLIFE[1]),
    rating: "4.81",
    reviewsCount: 88,
    featured: true,
  },
  {
    title: "Elementaita Cliff Cottage",
    slug: "elementaita-cliff-cottage",
    description:
      "Our stone cottage on the tranquil cliffs above Lake Elementaita, a Ramsar wetland humming with pelicans and buffalo. Soak in the hot tub as the sun sets behind the Eburru range.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Lake Elementaita",
    hostName: "Priya Nair",
    hostSince: 2018,
    hostBio: "I traded a city desk for lake sunsets and never looked back.",
    superhost: true,
    pricePerNight: 24500,
    cleaningFee: 2500,
    locationName: "Lake Elementaita",
    region: "Rift Valley Lakes",
    county: "Nakuru",
    latitude: "-0.453000",
    longitude: "36.248000",
    bedrooms: 2,
    beds: 3,
    bathrooms: "2",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Lake view", "Hot tub", "Kitchen", "Garden", "Air conditioning", "Self-check-in", "Bird watching", "Free parking", "Coffee & tea", "Family friendly", "Security 24/7"],
    highlights: ["Ramsar-listed wetland", "Sunset hot tub", "Pelican & buffalo views"],
    imageUrls: imgs(POOLS[0], ROOMS[4], LAKES[3], TENTS[7], ROOMS[1], LAKES[1]),
    rating: "4.83",
    reviewsCount: 104,
    featured: false,
  },

  // ---------------- SAMBURU ----------------
  {
    title: "Ewaso River Tented Camp",
    slug: "ewaso-river-tented-camp",
    description:
      "My camp tucked under towering acacia on the banks of the Ewaso Ng'iro — leopard and elephant territory, and home to the rare Samburu Special Five: reticulated giraffe, Grevy's zebra, beisa oryx, gerenuk and Somali ostrich.",
    propertyType: "tented_camp",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Samburu NR",
    hostName: "Yusuf Ali",
    hostSince: 2015,
    hostBio: "Samburu through and through. My trackers can read the river like a book.",
    superhost: true,
    pricePerNight: 33000,
    cleaningFee: 3500,
    locationName: "Samburu National Reserve",
    region: "Samburu",
    county: "Samburu",
    latitude: "0.553000",
    longitude: "37.519000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "River view", "Game drives included", "Breakfast included", "Sundowner cocktails", "Mosquito nets", "Hot showers", "Solar power", "Eco-friendly", "Nature walks", "Coffee & tea"],
    highlights: ["The Samburu Special Five", "Leopards on the riverbank", "Samburu cultural evenings"],
    imageUrls: imgs(TENTS[4], WILDLIFE[5], ROOMS[5], KILIMANJARO[1], POOLS[2], TENTS[7]),
    rating: "4.87",
    reviewsCount: 121,
    featured: false,
  },
  {
    title: "Buffalo Springs Bush Cottage",
    slug: "buffalo-springs-bush-cottage",
    description:
      "Our cottage across the river from Samburu, overlooking a natural spring that draws endless game. A self-catering kitchen and a fire boma make the dry north feel like an oasis home.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Buffalo Springs",
    hostName: "Sofia Garcia",
    hostSince: 2017,
    hostBio: "I run our community school sponsorship from cottage proceeds — your stay builds classrooms.",
    superhost: false,
    pricePerNight: 22000,
    cleaningFee: 3000,
    locationName: "Buffalo Springs National Reserve",
    region: "Samburu",
    county: "Isiolo",
    latitude: "0.612000",
    longitude: "37.556000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 3,
    amenities: ["Free Wi-Fi", "Game drives included", "Kitchen", "Air conditioning", "Hot showers", "Self-check-in", "Wildlife viewing", "Bonfire pit", "Airport transfers", "Laundry service", "Coffee & tea", "Security 24/7"],
    highlights: ["Spring-fed game magnet", "Self-catering bush home", "Community-impact stays"],
    imageUrls: imgs(POOLS[3], ROOMS[2], WILDLIFE[6], TENTS[1], KILIMANJARO[4], ROOMS[8]),
    rating: "4.78",
    reviewsCount: 67,
    featured: false,
  },

  // ---------------- MOUNT KENYA ----------------
  {
    title: "Naro Moru River Cottage",
    slug: "naro-moru-river-cottage",
    description:
      "Our riverside cottage on the lower slopes of Mount Kenya, the perfect base camp for trekkers and slow-travellers. Log fires, forest walks and trout fishing in the stream outside your door.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Mount Kenya NP",
    hostName: "Emily Davis",
    hostSince: 2016,
    hostBio: "Expedition leader for Sirimon and Naro Moru routes. I'll brief your summit attempt over dinner.",
    superhost: true,
    pricePerNight: 16000,
    cleaningFee: 1500,
    locationName: "Mount Kenya National Park",
    region: "Mount Kenya",
    county: "Nyeri",
    latitude: "-0.181000",
    longitude: "37.271000",
    bedrooms: 2,
    beds: 3,
    bathrooms: "2",
    maxGuests: 5,
    amenities: ["Free Wi-Fi", "Mountain view", "Fireplace", "Kitchen", "Garden", "Hot showers", "Self-check-in", "Nature walks", "Free parking", "Coffee & tea", "Family friendly", "Workspace"],
    highlights: ["Mount Kenya base camp", "Trout stream on-site", "Cosy log fires"],
    imageUrls: imgs(ROOMS[5], POOLS[3], KILIMANJARO[6], ROOMS[8], TENTS[7], ROOMS[1]),
    rating: "4.8",
    reviewsCount: 76,
    featured: false,
  },
  {
    title: "Aberdare Treehouse Cabin",
    slug: "aberdare-treehouse-cabin",
    description:
      "Our off-grid treehouse cabin deep in the Aberdare cloud forest, built around a floodlit clearing where elephant and buffalo emerge after dark. Misty waterfalls and canopy walks by day.",
    propertyType: "eco_camp",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Aberdare NP",
    hostName: "Amani Otieno",
    hostSince: 2013,
    hostBio: "Forest ranger for fifteen years. I'll lead you to the hidden waterfalls at dawn.",
    superhost: true,
    pricePerNight: 21500,
    cleaningFee: 3000,
    locationName: "Aberdare National Park",
    region: "Mount Kenya",
    county: "Nyeri",
    latitude: "-0.389000",
    longitude: "36.712000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Forest view", "Breakfast included", "Fireplace", "Hot showers", "Solar power", "Eco-friendly", "Wildlife viewing", "Nature walks", "Bird watching", "Coffee & tea", "Security 24/7"],
    highlights: ["Treehouse in cloud forest", "Floodlit forest clearing", "Hidden waterfall walks"],
    imageUrls: imgs(ROOMS[1], TENTS[7], POOLS[2], KILIMANJARO[6], WILDLIFE[1], ROOMS[5]),
    rating: "4.77",
    reviewsCount: 58,
    featured: false,
  },

  // ---------------- TSAVO ----------------
  {
    title: "Tsavo Red Earth Bush Cottage",
    slug: "tsavo-red-earth-bush-cottage",
    description:
      "Our cottage in the dust-red heart of Kenya's largest park, watching a waterhole where the famous red elephants of Tsavo come to drink. Self-catering, vast, wild and gloriously uncrowded.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Tsavo East",
    hostName: "Daniel Kimani",
    hostSince: 2014,
    hostBio: "Tsavo is enormous and untamed — I'll show you the secret dams and lava flows.",
    superhost: true,
    pricePerNight: 20000,
    cleaningFee: 3000,
    locationName: "Tsavo East National Park",
    region: "Tsavo",
    county: "Taita-Taveta",
    latitude: "-2.832000",
    longitude: "38.491000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Game drives included", "Kitchen", "Air conditioning", "Hot showers", "Self-check-in", "Wildlife viewing", "Bonfire pit", "Airport transfers", "Laundry service", "Coffee & tea", "Security 24/7"],
    highlights: ["Famous red elephants", "Private waterhole view", "Kenya's largest wilderness"],
    imageUrls: imgs(WILDLIFE[5], KILIMANJARO[0], POOLS[4], ROOMS[1], TENTS[1], WILDLIFE[6]),
    rating: "4.82",
    reviewsCount: 99,
    featured: false,
  },
  {
    title: "Mzima Springs Eco Camp",
    slug: "mzima-springs-eco-camp",
    description:
      "My camp beside the crystal-clear Mzima Springs, where you can watch hippos and crocodiles through an underwater viewing chamber. Palm groves, chattering monkeys and a natural pool.",
    propertyType: "eco_camp",
    roomType: "entire",
    priceTier: "budget",
    landmark: "Tsavo West",
    hostName: "Fatuma Hassan",
    hostSince: 2020,
    hostBio: "I lead the spring's clean-up crew. The water here is some of the purest in Kenya.",
    superhost: false,
    pricePerNight: 13000,
    cleaningFee: 2000,
    locationName: "Tsavo West National Park",
    region: "Tsavo",
    county: "Taita-Taveta",
    latitude: "-3.012000",
    longitude: "38.172000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Game drives included", "Breakfast included", "Solar power", "Eco-friendly", "Hot showers", "Mosquito nets", "Nature walks", "Bird watching", "Coffee & tea", "Wildlife viewing"],
    highlights: ["Underwater hippo chamber", "Crystal-clear springs", "Natural swimming pool"],
    imageUrls: imgs(TENTS[5], LAKES[1], ROOMS[6], POOLS[2], KILIMANJARO[4], WILDLIFE[1]),
    rating: "4.74",
    reviewsCount: 51,
    featured: false,
  },

  // ---------------- NAIROBI ----------------
  {
    title: "Westlands Apartment",
    slug: "westlands-apartment",
    description:
      "My modern, secure one-bedroom apartment in Nairobi's Westlands district — fast Wi-Fi, a workspace and a city skyline view. The ideal budget-friendly base for digital nomads and safari stopovers.",
    propertyType: "apartment",
    roomType: "entire",
    priceTier: "budget",
    landmark: "Westlands",
    hostName: "Sarah Johnson",
    hostSince: 2017,
    hostBio: "Digital nomad turned host. My place is set up exactly how I'd want to work remotely.",
    superhost: true,
    pricePerNight: 9000,
    cleaningFee: 900,
    locationName: "Nairobi (Westlands)",
    region: "Nairobi",
    county: "Nairobi",
    latitude: "-1.296000",
    longitude: "36.810000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Air conditioning", "Workspace", "Kitchen", "Hot showers", "Gym", "Self-check-in", "Free parking", "Security 24/7", "Coffee & tea"],
    highlights: ["Workspace for digital nomads", "Secure Westlands tower", "Self-check-in"],
    imageUrls: imgs(ROOMS[6], ROOMS[3], BALCONY[5], ROOMS[7], ROOMS[1], POOLS[0]),
    rating: "4.68",
    reviewsCount: 118,
    featured: false,
  },
  {
    title: "Karen Forest Villa",
    slug: "karen-forest-villa",
    description:
      "Our serene home tucked against the Ngong Forest in Karen, with mature gardens, a heated pool and giraffe-and-bushbuck visitors. Minutes from the Giraffe Centre and Nairobi National Park.",
    propertyType: "bush_villa",
    roomType: "entire",
    priceTier: "luxury",
    landmark: "Ngong Forest",
    hostName: "Grace Wanjiru",
    hostSince: 2015,
    hostBio: "I run a small wildlife sanctuary next door — bushbuck and the occasional giraffe wander through.",
    superhost: true,
    pricePerNight: 55000,
    cleaningFee: 5500,
    locationName: "Nairobi (Karen)",
    region: "Nairobi",
    county: "Nairobi",
    latitude: "-1.324000",
    longitude: "36.705000",
    bedrooms: 3,
    beds: 4,
    bathrooms: "3",
    maxGuests: 6,
    amenities: ["Free Wi-Fi", "Heated pool", "Garden view", "Fireplace", "Air conditioning", "Kitchen", "Self-check-in", "Breakfast included", "Free parking", "Nature walks", "Security 24/7", "Laundry service"],
    highlights: ["On the edge of Ngong Forest", "Heated pool & gardens", "Wildlife in the garden"],
    imageUrls: imgs(ROOMS[5], POOLS[3], ROOMS[8], TENTS[7], WILDLIFE[8], ROOMS[1]),
    rating: "4.91",
    reviewsCount: 89,
    featured: true,
  },
  {
    title: "Karen Giraffe Cottage",
    slug: "karen-giraffe-cottage",
    description:
      "Our leafy cottage in Karen, minutes from the Giraffe Centre and Nairobi National Park — the only capital-city park on Earth. Endangered Rothschild's giraffe may poke their heads over your breakfast table.",
    propertyType: "cottage",
    roomType: "entire",
    priceTier: "mid",
    landmark: "Giraffe Centre",
    hostName: "Grace Wanjiru",
    hostSince: 2018,
    hostBio: "I volunteer at the giraffe sanctuary. Breakfast with a giraffe is my daily alarm clock.",
    superhost: true,
    pricePerNight: 17500,
    cleaningFee: 1500,
    locationName: "Nairobi (Karen)",
    region: "Nairobi",
    county: "Nairobi",
    latitude: "-1.319700",
    longitude: "36.708000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1.5",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Garden", "Breakfast included", "Kitchen", "Air conditioning", "Hot showers", "Self-check-in", "Free parking", "Family friendly", "Coffee & tea", "Nature walks", "Wildlife viewing"],
    highlights: ["Minutes to Giraffe Centre", "Adjacent to Nairobi NP", "Breakfast with giraffes"],
    imageUrls: imgs(ROOMS[4], LAKES[3], POOLS[0], ROOMS[8], TENTS[7], WILDLIFE[8]),
    rating: "4.88",
    reviewsCount: 169,
    featured: false,
  },
];

// ---- Review generation ----
const REVIEWERS = [
  "Amani Otieno", "Njeri Kamau", "David Mwangi", "Sarah Johnson", "Liam O'Connor",
  "Wei Chen", "Priya Nair", "Tom Becker", "Fatuma Hassan", "Grace Wanjiru",
  "Marco Rossi", "Emily Davis", "Kofi Mensah", "Sofia Garcia", "Daniel Kimani",
  "Hannah Schmidt", "Yusuf Ali", "Chloe Martin", "Brian Otieno", "Linet Akinyi",
  "Hiroshi Tanaka", "Lucía Fernández", "Omar Farah", "Anika Patel", "James Carter",
];

const COMMENTS = [
  "Unforgettable — our host made us feel like family from the moment we arrived.",
  "The home was spotless, well-stocked and exactly as pictured. Self check-in was a breeze.",
  "Waking up to wildlife passing the deck is something we'll never forget.",
  "Brilliant value and genuinely warm Kenyan hospitality. We're already planning to return.",
  "The kitchen had everything we needed and the location was perfect for exploring.",
  "Super responsive host, comfy beds and a stunning view. Highly recommend.",
  "The kids are still talking about breakfast with the animals wandering past.",
  "A real home in the wild — authentic, peaceful and beautifully kept.",
  "From the welcome to the farewell, every thoughtful detail was spot on.",
  "Five-star hosting in the middle of nowhere. Book it without hesitation.",
];

const MONTHS = [
  "Jan 2025", "Feb 2025", "Mar 2025", "Apr 2025", "May 2025", "Jun 2025",
  "Jul 2025", "Aug 2025", "Sep 2025", "Oct 2025", "Nov 2025", "Dec 2024",
];

function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return h;
}

function makeReviews(listingId: number, slug: string, rating: number, maxN: number) {
  const n = Math.min(maxN, 3);
  if (n <= 0) return [];
  const seed = hashString(slug);
  const out = [];
  for (let i = 0; i < n; i++) {
    const idx = (seed + i * 7) % REVIEWERS.length;
    const c = (seed + i * 13) % COMMENTS.length;
    const m = (seed + i * 5) % MONTHS.length;
    out.push({
      listingId,
      guestName: REVIEWERS[idx],
      avatar: `https://i.pravatar.cc/96?img=${(idx % 70) + 1}`,
      rating: i === n - 1 ? Math.max(4, Math.round(rating)) : 5,
      comment: COMMENTS[c],
      stayedOn: MONTHS[m],
    });
  }
  return out;
}

async function main() {
  console.log("🧹 Clearing existing data...");
  await db.execute(sql`truncate table bookings, reviews, listings restart identity cascade`);

  console.log(`🌱 Inserting ${LISTINGS.length} listings...`);
  let reviewTotal = 0;
  for (const item of LISTINGS) {
    const values = {
      ...item,
      priceTier: item.priceTier ?? tierForPrice(item.pricePerNight),
    };
    const [row] = await db.insert(listings).values(values).returning({ id: listings.id });
    const reviewRows = makeReviews(row.id, item.slug!, Number(item.rating), item.reviewsCount ?? 0);
    if (reviewRows.length) {
      await db.insert(reviews).values(reviewRows);
      reviewTotal += reviewRows.length;
    }
  }

  console.log(`✅ Done. Inserted ${LISTINGS.length} listings and ${reviewTotal} reviews.`);
}

main()
  .then(() => process.exit(0))
  .catch(async (err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
