import { db } from "@/db";
import { bookings, listings, reviews } from "@/db/schema";
import { sql } from "drizzle-orm";
import { tierForPrice } from "@/lib/constants";

// Real Kenya photography (Pexels) used across the catalogue.
const px = (id: number, w = 1600, h = 1067, ext = "jpeg") =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.${ext}?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;

const TENTS = [17831034, 18671249, 1001437, 9491326, 18717287, 28157088, 30041430, 17831035];
const WILDLIFE = [18960157, 5306128, 30125343, 5306140, 35717988, 20335122, 19294855, 31055413, 30705107, 20865860];
const KILIMANJARO = [35718707, 19267298, 15994021, 29093739, 5109704, 37808650, 15993988];
const ROOMS = [28148280, 6394651, 6434592, 29000312, 6876834, 14025910, 28148281, 2736384, 14025911, 29006838];
const BEACH = [27742235, 20693413, 20693411, 23234936, 36216421, 10489622, 12497747, 7952876];
const LAKES = [7734639, 33473218, 12573131, 33473215, 20653797, 20653421, 30153995];
const POOLS = [12387911, 20975737, 37790193, 20975726, 20975727, 6129994, 5041953];
const DIANI = [33719857, 27742223, 33629231, 8157590, 1591379, 37476348, 2549084];
const BALCONY = [14025912, 20221437, 13205670, 38960514, 11978834, 27349378, 14917459, 33963776];
const SWAHILI = [33802298, 25254990, 18896097];

const imgs = (...ids: number[]) => ids.map((id) => px(id));

type SeedListing = typeof listings.$inferInsert;

// ---------------------------------------------------------------- LISTINGS
// 15 real, well-known Kenyan properties. Rates are published seasonal prices
// (green/low and peak) converted to KES; coordinates are real map locations.
const RAW_LISTINGS: SeedListing[] = [
  {
    title: "Angama Mara",
    slug: "angama-mara",
    description:
      "Thirty tented suites suspended high on the Oloololo Escarpment, 300 metres above the floor of the Great Rift Valley and the Mara Triangle below. All-inclusive safari living: private game drives, walking safaris, all meals and drinks, laundry and airstrip transfers — with arguably the finest views in the Mara.",
    propertyType: "safari_lodge",
    roomType: "entire",
    landmark: "Oloololo Escarpment",
    hostName: "Angama Limited",
    hostSince: 2015,
    hostBio: "Award-winning lodge built with the Maasai community on the escarpment rim. Known for hot-air balloon dawns and migration-season crossings.",
    superhost: true,
    pricePerNight: 350000,
    peakPricePerNight: 477000,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    website: "https://www.angama.com",
    locationName: "Maasai Mara (Mara Triangle)",
    region: "Maasai Mara",
    county: "Narok",
    latitude: "-1.266700",
    longitude: "35.033300",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 2,
    amenities: [
      "Game drives included", "Walking safaris", "All meals & drinks", "Laundry service", "Wi-Fi",
      "Airstrip transfers", "Hot-air balloon (extra)", "Kilimanjaro views", "Sundowner cocktails",
      "Masai cultural visits", "Emergency evacuation cover", "Security 24/7",
    ],
    highlights: ["Mara Triangle front-row", "Escarpment cliff-edge suites", "Balloon rides at dawn"],
    imageUrls: imgs(TENTS[0], WILDLIFE[4], KILIMANJARO[1], ROOMS[4], POOLS[2], TENTS[7], WILDLIFE[2], KILIMANJARO[3]),
    rating: "4.96",
    reviewsCount: 328,
    featured: true,
  },
  {
    title: "Governors' Camp",
    slug: "governors-camp",
    description:
      "The original classic tented camp, on the banks of the Mara River since 1972 — front-row seats to the great wildebeest river crossings. Full-board stays with two to three shared game drives a day, professional guides, airstrip transfers and daily laundry in the heart of the Maasai Mara.",
    propertyType: "tented_camp",
    roomType: "entire",
    landmark: "Mara River",
    hostName: "Governors' Camp Collection",
    hostSince: 1972,
    hostBio: "A Kenyan safari institution for over half a century, family-run and set on a private bend of the Mara River.",
    superhost: true,
    pricePerNight: 117000,
    peakPricePerNight: 258000,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.governorscamp.com",
    locationName: "Maasai Mara National Reserve",
    region: "Maasai Mara",
    county: "Narok",
    latitude: "-1.279500",
    longitude: "35.139700",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 2,
    amenities: [
      "Game drives included", "Full board", "Shared drives daily", "Laundry service", "Wi-Fi",
      "Airstrip transfers", "Sundowner cocktails", "Bush breakfasts", "Bird watching",
      "Maasai cultural visits", "Solar power", "Security 24/7",
    ],
    highlights: ["The original Mara camp", "River-crossing front-row", "Half a century of safaris"],
    imageUrls: imgs(TENTS[1], WILDLIFE[2], ROOMS[5], TENTS[7], WILDLIFE[8], POOLS[2], WILDLIFE[1], TENTS[0]),
    rating: "4.86",
    reviewsCount: 712,
    featured: true,
  },
  {
    title: "Entim Camp",
    slug: "entim-camp",
    description:
      "An intimate camp set centrally in the Maasai Mara on the Talek–Mara river confluence — the very migration corridors where the herds cross. All-inclusive luxury tents with house drinks, shared game drives, laundry and meals as the Mara plays out beyond your canvas walls.",
    propertyType: "tented_camp",
    roomType: "entire",
    landmark: "Talek River",
    hostName: "Entim Mara Camp",
    hostSince: 2012,
    hostBio: "A small, family-run camp built on the migration river crossroads — maasai guides lead every drive.",
    superhost: true,
    pricePerNight: 181000,
    peakPricePerNight: 283000,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.entimcamp.com",
    locationName: "Maasai Mara National Reserve",
    region: "Maasai Mara",
    county: "Narok",
    latitude: "-1.383300",
    longitude: "35.066700",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: [
      "Game drives included", "All meals & drinks", "House drinks", "Laundry service", "Wi-Fi",
      "Sundowner cocktails", "Bush breakfasts", "Walking safaris", "Bird watching",
      "Maasai cultural visits", "Solar power", "Security 24/7",
    ],
    highlights: ["On the migration crossing", "Central Mara position", "All-inclusive luxury"],
    imageUrls: imgs(TENTS[4], WILDLIFE[1], ROOMS[1], KILIMANJARO[4], TENTS[6], WILDLIFE[3], TENTS[5], WILDLIFE[6]),
    rating: "4.9",
    reviewsCount: 204,
    featured: false,
  },
  {
    title: "Amboseli Serena Safari Lodge",
    slug: "amboseli-serena-safari-lodge",
    description:
      "A Maasai-themed lodge deep inside Amboseli National Park, facing the snows of Kilimanjaro across the game-rich swamps. Watch elephant families file to the waterhole from the pool terrace — the classic Amboseli postcard, live.",
    propertyType: "safari_lodge",
    roomType: "entire",
    landmark: "Amboseli NP",
    hostName: "Serena Hotels",
    hostSince: 1971,
    hostBio: "Serena's collection of lodges sits at Kenya's wildest viewpoints; this one is built on a private spring in Amboseli.",
    superhost: true,
    pricePerNight: 44000,
    peakPricePerNight: 56000,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.serenahotels.com/amboseli",
    locationName: "Amboseli National Park",
    region: "Amboseli",
    county: "Kajiado",
    latitude: "-2.638900",
    longitude: "37.250000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1",
    maxGuests: 4,
    amenities: [
      "Game drives included", "Pool", "Wi-Fi", "24-hour room service", "Breakfast included",
      "Kilimanjaro views", "Wildlife viewing", "Sundowner cocktails", "Maasai cultural visits",
      "Laundry service", "Bar & restaurant", "Security 24/7",
    ],
    highlights: ["Kilimanjaro views on site", "Elephants at the waterhole", "Inside the national park"],
    imageUrls: imgs(KILIMANJARO[2], KILIMANJARO[0], POOLS[1], ROOMS[6], WILDLIFE[5], KILIMANJARO[5], WILDLIFE[0], KILIMANJARO[4]),
    rating: "4.74",
    reviewsCount: 946,
    featured: false,
  },
  {
    title: "Elephant Bedroom Camp",
    slug: "elephant-bedroom-camp",
    description:
      "Elegant 'bedroom' tents on the banks of the Ewaso Ng'iro in Samburu, where elephant families wander through camp between river visits. Home turf of the rare Samburu Special Five: reticulated giraffe, Grevy's zebra, beisa oryx, gerenuk and Somali ostrich.",
    propertyType: "safari_lodge",
    roomType: "entire",
    landmark: "Ewaso Ng'iro River",
    hostName: "Elephant Bedroom Camp",
    hostSince: 2009,
    hostBio: "A boutique tented camp famed for elephants roaming the riverbank at arm's length.",
    superhost: true,
    pricePerNight: 113500,
    peakPricePerNight: 195000,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.elephantbedroomcamp.com",
    locationName: "Samburu National Reserve",
    region: "Samburu",
    county: "Samburu",
    latitude: "0.589400",
    longitude: "37.603300",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 2,
    amenities: [
      "Game drives included", "All meals & drinks", "Sundowner cocktails", "Laundry service", "Wi-Fi",
      "Nature walks", "River views", "Bird watching", "Solar power", "Samburu cultural evenings",
      "Airstrip transfers", "Security 24/7",
    ],
    highlights: ["Elephants in camp", "The Samburu Special Five", "Riverfront bedroom tents"],
    imageUrls: imgs(TENTS[3], WILDLIFE[5], ROOMS[3], POOLS[2], TENTS[0], WILDLIFE[6], WILDLIFE[4], KILIMANJARO[1]),
    rating: "4.92",
    reviewsCount: 176,
    featured: true,
  },
  {
    title: "Ol Pejeta Bush Camp",
    slug: "ol-pejeta-bush-camp",
    description:
      "A six-tent eco camp on East Africa's largest black rhino sanctuary, and home to the last two northern white rhinos on Earth. Solar-powered luxury on the Ewaso Ng'iro, with guided walks, night drives and conservation experiences that give back to the sanctuary.",
    propertyType: "eco_camp",
    roomType: "entire",
    landmark: "Ol Pejeta Conservancy",
    hostName: "Asilia Africa",
    hostSince: 2014,
    hostBio: "Asilia runs a small collection of purpose-built camps; Ol Pejeta is their conservation flagship in Laikipia.",
    superhost: true,
    pricePerNight: 155000,
    peakPricePerNight: 238000,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.asiliaafrica.com/ol-pejeta-bush-camp",
    locationName: "Ol Pejeta Conservancy",
    region: "Laikipia",
    county: "Laikipia",
    latitude: "0.062800",
    longitude: "36.904400",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1",
    maxGuests: 4,
    amenities: [
      "Game drives included", "Nature walks", "Night drives", "All meals", "Laundry service",
      "Conservation visits", "Solar power", "Eco-friendly", "Wi-Fi", "Wildlife viewing",
      "Coffee & tea", "Security 24/7",
    ],
    highlights: ["Black rhino sanctuary", "Last northern white rhinos", "Conservation experiences"],
    imageUrls: imgs(TENTS[5], WILDLIFE[3], ROOMS[0], POOLS[6], WILDLIFE[7], KILIMANJARO[4], WILDLIFE[1], TENTS[2]),
    rating: "4.88",
    reviewsCount: 92,
    featured: false,
  },
  {
    title: "Finch Hattons Luxury Tented Camp",
    slug: "finch-hattons",
    description:
      "The grande dame of Tsavo West — a colonial-era luxury camp on the banks of a natural spring, where lions, elephants and buffalo come to drink beside the pool. Tented suites, candlelit dinners and private game drives across Kenya's largest wilderness.",
    propertyType: "tented_camp",
    roomType: "entire",
    landmark: "Mzima Springs",
    hostName: "Finch Hattons Ltd",
    hostSince: 1996,
    hostBio: "A storied Tsavo camp rebuilt in the grand safari style — sundowners by the spring are legendary.",
    superhost: true,
    pricePerNight: 300000,
    peakPricePerNight: 374000,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.finchhattons.com",
    locationName: "Tsavo West National Park",
    region: "Tsavo",
    county: "Taita-Taveta",
    latitude: "-2.933300",
    longitude: "37.900000",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 2,
    amenities: [
      "Game drives included", "Pool", "All meals", "Laundry service", "Wi-Fi",
      "Sundowner cocktails", "Bush breakfasts", "Spring-water views", "Bird watching",
      "Airstrip transfers", "Bar & restaurant", "Security 24/7",
    ],
    highlights: ["Lions by the spring", "Colonial-era grandeur", "Kenya's largest wilderness"],
    imageUrls: imgs(POOLS[2], TENTS[6], WILDLIFE[5], ROOMS[1], KILIMANJARO[0], TENTS[1], WILDLIFE[3], POOLS[5]),
    rating: "4.95",
    reviewsCount: 141,
    featured: true,
  },
  {
    title: "Serena Mountain Lodge",
    slug: "serena-mountain-lodge",
    description:
      "A tree-lodge hidden in the montane forest of Mount Kenya's slopes, built around a floodlit waterhole and salt lick where elephant, buffalo and bongo emerge after dark. Rustic-cosy rooms, log fires and forest walks beneath the glaciered peaks.",
    propertyType: "safari_lodge",
    roomType: "entire",
    landmark: "Mount Kenya NP",
    hostName: "Serena Hotels",
    hostSince: 1976,
    hostBio: "Serena's mountain hideaway — a canopy-level lodge watching the forest by floodlight.",
    superhost: false,
    pricePerNight: 29700,
    peakPricePerNight: 42000,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.serenahotels.com/serena-mountain-lodge",
    locationName: "Mount Kenya National Park",
    region: "Mount Kenya",
    county: "Nyeri",
    latitude: "-0.316700",
    longitude: "37.150000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1",
    maxGuests: 4,
    amenities: [
      "Wildlife viewing", "Floodlit waterhole", "Breakfast included", "Wi-Fi", "Fireplace",
      "Nature walks", "Bird watching", "Hot showers", "Bar & restaurant", "Laundry service",
      "Coffee & tea", "Free parking",
    ],
    highlights: ["Night game at the salt lick", "Cloud-forest setting", "Mount Kenya base camp"],
    imageUrls: imgs(ROOMS[5], KILIMANJARO[6], POOLS[3], ROOMS[8], WILDLIFE[1], TENTS[7], WILDLIFE[3], ROOMS[2]),
    rating: "4.7",
    reviewsCount: 823,
    featured: false,
  },
  {
    title: "Lake Naivasha Sopa Resort",
    slug: "lake-naivasha-sopa-resort",
    description:
      "A lakeside resort spread along the shore of the Rift Valley's freshwater jewel, where hippos graze the lawns at dusk and fish eagles call overhead. Boat to Crescent Island and walk among giraffe, zebra and buffalo — a perfect Rift Valley escape.",
    propertyType: "safari_lodge",
    roomType: "entire",
    landmark: "Lake Naivasha",
    hostName: "Sopa Lodges",
    hostSince: 1997,
    hostBio: "Sopa's Rift Valley resort — manicured gardens meeting the wild shore of Lake Naivasha.",
    superhost: false,
    pricePerNight: 52900,
    peakPricePerNight: 78000,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.sopalodges.com",
    locationName: "Lake Naivasha",
    region: "Rift Valley Lakes",
    county: "Nakuru",
    latitude: "-0.811100",
    longitude: "36.391700",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1",
    maxGuests: 4,
    amenities: [
      "Lake view", "Pool", "Breakfast included", "Wi-Fi", "Boat trips (extra)",
      "Bird watching", "Garden", "Bar & restaurant", "Laundry service", "Free parking",
      "Family friendly", "Security 24/7",
    ],
    highlights: ["Hippos on the lawn", "Crescent Island walk", "Rift Valley sunsets"],
    imageUrls: imgs(LAKES[0], LAKES[2], POOLS[0], ROOMS[3], LAKES[3], ROOMS[7], LAKES[1], POOLS[3]),
    rating: "4.66",
    reviewsCount: 1045,
    featured: false,
  },
  {
    title: "Giraffe Manor",
    slug: "giraffe-manor",
    description:
      "The iconic 1932 manor in Nairobi's Karen suburb, where resident Rothschild giraffes poke their heads through the breakfast windows each morning. An elegant step back in time and the world's most photogenic hotel — minutes from the Giraffe Centre and Nairobi National Park.",
    propertyType: "safari_lodge",
    roomType: "entire",
    landmark: "Karen · Lang'ata",
    hostName: "The Safari Collection",
    hostSince: 1932,
    hostBio: "A Nairobi icon and conservation pioneer — the manor's giraffes are ambassadors for the endangered Rothschild subspecies.",
    superhost: true,
    pricePerNight: 301500,
    peakPricePerNight: 401000,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    website: "https://www.thesafaricollection.com/giraffe-manor",
    locationName: "Nairobi (Karen)",
    region: "Nairobi",
    county: "Nairobi",
    latitude: "-1.375600",
    longitude: "36.744700",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: [
      "Breakfast included", "Giraffe feeding", "All meals", "Wi-Fi", "Garden",
      "Nature walks", "Conservation visits", "Fireplace", "Bar & restaurant", "Laundry service",
      "Airstrip transfers", "Security 24/7",
    ],
    highlights: ["Giraffes at breakfast", "1932 manor house", "Conservation legacy"],
    imageUrls: imgs(WILDLIFE[8], ROOMS[4], KILIMANJARO[1], TENTS[7], POOLS[4], ROOMS[0], WILDLIFE[2], BALCONY[3]),
    rating: "4.97",
    reviewsCount: 611,
    featured: true,
  },
  {
    title: "Kinondo Kwetu",
    slug: "kinondo-kwetu",
    description:
      "Barefoot luxury on a private stretch of Galu Beach: a fully inclusive eco-resort with no cars, just sand paths under the palms. All meals, selected drinks, beachfront gym, pools and non-motorised water sports — plus snorkelling on the reef at low tide.",
    propertyType: "beach_resort",
    roomType: "entire",
    landmark: "Galu Beach",
    hostName: "Kinondo Kwetu Resort",
    hostSince: 1998,
    hostBio: "A Kenyan-owned barefoot-luxury resort on the south coast — all-inclusive, eco-minded and wonderfully unplugged.",
    superhost: true,
    pricePerNight: 139500,
    peakPricePerNight: 185000,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.kinondokwetu.com",
    locationName: "Diani Beach (Galu)",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.366700",
    longitude: "39.566700",
    bedrooms: 3,
    beds: 3,
    bathrooms: "1",
    maxGuests: 6,
    amenities: [
      "All meals included", "Selected drinks", "Beach access", "Pool", "Gym",
      "Snorkelling included", "Non-motorised water sports", "Yoga & spa", "Wi-Fi",
      "Ocean view", "Laundry service", "Security 24/7",
    ],
    highlights: ["Private Galu beachfront", "Truly all-inclusive", "Barefoot, no-cars ethos"],
    imageUrls: imgs(BEACH[0], DIANI[1], POOLS[0], ROOMS[1], BEACH[4], BALCONY[6], BEACH[2], DIANI[4]),
    rating: "4.94",
    reviewsCount: 268,
    featured: true,
  },
  {
    title: "Diani Sea Lodge",
    slug: "diani-sea-lodge",
    description:
      "A classic all-inclusive beach resort on Diani's white sands — a palm garden sloping to the reef at low tide. Board sports, a dive centre and Swahili buffets, with the beach bars of Diani a stroll along the sand.",
    propertyType: "beach_resort",
    roomType: "entire",
    landmark: "Diani Beach",
    hostName: "Diani Sea Lodge",
    hostSince: 1977,
    hostBio: "One of Diani's original resorts, welcoming families and honeymooners for nearly fifty years.",
    superhost: false,
    pricePerNight: 26000,
    peakPricePerNight: 33700,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.dianisealodge.com",
    locationName: "Diani Beach",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.313700",
    longitude: "39.583100",
    bedrooms: 3,
    beds: 3,
    bathrooms: "1",
    maxGuests: 6,
    amenities: [
      "All meals included", "Pool", "Beach access", "Dive centre", "Wi-Fi", "Air conditioning",
      "Bar & restaurant", "Watersports (extra)", "Kids club", "Laundry service",
      "Free parking", "Security 24/7",
    ],
    highlights: ["All-inclusive Diani classic", "Reef at low tide", "On-site dive centre"],
    imageUrls: imgs(BEACH[1], DIANI[0], POOLS[4], ROOMS[2], BEACH[5], ROOMS[8], BEACH[4], POOLS[2]),
    rating: "4.71",
    reviewsCount: 1284,
    featured: false,
  },
  {
    title: "The Sands at Nomad",
    slug: "the-sands-at-nomad",
    description:
      "A boutique beach hotel perched on Diani's beachfront, where contemporary Swahili design meets candlelit dinners and a legendary pool at the tide's edge. Steps to the beach bars, dive shops and the reef — the sweet spot of Diani.",
    propertyType: "beach_resort",
    roomType: "entire",
    landmark: "Diani Beach",
    hostName: "Hemmingways Collection",
    hostSince: 2000,
    hostBio: "An award-winning Diani boutique hotel known for its seafront dining and serene pool.",
    superhost: true,
    pricePerNight: 36800,
    peakPricePerNight: 56200,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.thesandsatnomad.com",
    locationName: "Diani Beach",
    region: "Coast",
    county: "Kwale",
    latitude: "-4.347800",
    longitude: "39.590300",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1",
    maxGuests: 4,
    amenities: [
      "Pool", "Beach access", "Breakfast included", "Wi-Fi", "Air conditioning",
      "Bar & restaurant", "Spa", "Dive centre (extra)", "Ocean view", "Laundry service",
      "Free parking", "Security 24/7",
    ],
    highlights: ["Boutique beachfront design", "Legendary pool", "Diani's best seafront dining"],
    imageUrls: imgs(POOLS[1], BEACH[2], DIANI[3], ROOMS[7], BALCONY[0], BEACH[6], BEACH[1], DIANI[1]),
    rating: "4.83",
    reviewsCount: 452,
    featured: true,
  },
  {
    title: "Medina Palms",
    slug: "medina-palms-watamu",
    description:
      "A Swahili-inspired village of suites and private villas on Watamu's lagoon-facing beach, fringing the protected marine park. Pools, a beachfront spa, and turtle season at your doorstep — as the sun sets over Mida Creek.",
    propertyType: "beach_resort",
    roomType: "entire",
    landmark: "Watamu Marine Park",
    hostName: "Medina Palms Watamu",
    hostSince: 2013,
    hostBio: "An architectural love letter to the Swahili coast, built around courtyards, pools and the Indian Ocean.",
    superhost: true,
    pricePerNight: 28900,
    peakPricePerNight: 56100,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.medinapalms.com",
    locationName: "Watamu",
    region: "Coast",
    county: "Kilifi",
    latitude: "-3.360000",
    longitude: "39.995000",
    bedrooms: 4,
    beds: 4,
    bathrooms: "1",
    maxGuests: 8,
    amenities: [
      "Pool", "Beach access", "Breakfast included", "Wi-Fi", "Air conditioning", "Spa",
      "Bar & restaurant", "Snorkelling (extra)", "Ocean view", "Laundry service",
      "Free parking", "Security 24/7",
    ],
    highlights: ["Marine-park lagoon", "Swahili village design", "Turtle-nesting season"],
    imageUrls: imgs(POOLS[6], BEACH[5], ROOMS[3], BEACH[1], POOLS[2], ROOMS[0], BEACH[4], DIANI[5]),
    rating: "4.8",
    reviewsCount: 389,
    featured: true,
  },
  {
    title: "Peponi Hotel",
    slug: "peponi-hotel-lamu",
    description:
      "The legendary whitewashed dhow-era hotel on Lamu's seafront, welcoming sailors and wanderers since 1967. Carved Swahili doors, rooftop sundowners, and the old town's labyrinth of alleys a barefoot stroll away.",
    propertyType: "beach_resort",
    roomType: "entire",
    landmark: "Shela Beach",
    hostName: "Peponi Hotels Ltd",
    hostSince: 1967,
    hostBio: "Lamu's most storied address — part hotel, part island institution, run by the same family for generations.",
    superhost: true,
    pricePerNight: 31600,
    peakPricePerNight: 41900,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    website: "https://www.peponi-lamu.com",
    locationName: "Lamu (Shela)",
    region: "Coast",
    county: "Lamu",
    latitude: "-2.294800",
    longitude: "40.916000",
    bedrooms: 2,
    beds: 2,
    bathrooms: "1",
    maxGuests: 4,
    amenities: [
      "Breakfast included", "Rooftop terrace", "Beach access", "Wi-Fi", "Bar & restaurant",
      "Dhow trips (extra)", "Cultural visits", "Air conditioning", "Laundry service",
      "Ocean view", "Coffee & tea", "Security 24/7",
    ],
    highlights: ["Lamu legend since 1967", "Rooftop dhow sunsets", "Old town on your doorstep"],
    imageUrls: imgs(SWAHILI[0], BEACH[7], ROOMS[2], SWAHILI[1], BALCONY[5], ROOMS[5], SWAHILI[2], BEACH[3]),
    rating: "4.88",
    reviewsCount: 533,
    featured: false,
  },
  // ------------------------------------------------------------ LOCAL STAYS
  // Real budget stays for everyday Kenyan travellers — town guesthouses,
  // backpackers and campsites with researched indicative local rates.
  {
    title: "Milimani Backpackers",
    slug: "milimani-backpackers-nairobi",
    description:
      "Nairobi's classic budget backpackers in Milimani — clean dorms and private rooms a quick matatu hop from the CBD. Free breakfast, hot showers, a travel desk that sorts your safari or bus ticket, and a garden where travellers trade stories. The easiest bed in the city under four grand.",
    propertyType: "backpacker",
    roomType: "private",
    landmark: "Milimani · 10 min to CBD stages",
    hostName: "Milimani Backpackers",
    hostSince: 2010,
    hostBio: "Kenya's original backpacker hub — run by the same friendly team for over a decade.",
    superhost: true,
    pricePerNight: 3800,
    peakPricePerNight: 4500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.milimanibackpackers.com",
    locationName: "Milimani, Nairobi",
    region: "Nairobi",
    county: "Nairobi",
    latitude: "-1.294500",
    longitude: "36.775000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Hot showers", "Garden", "Travel desk", "Laundry service", "Self-catering kitchen", "Free parking", "Mosquito nets", "Security 24/7"],
    highlights: ["Under KES 4,000 in the city", "Free breakfast & hot showers", "Easy matatu access to town"],
    imageUrls: imgs(ROOMS[1], BALCONY[3], ROOMS[2], ROOMS[7], ROOMS[4], BALCONY[5], ROOMS[6], BALCONY[1]),
    rating: "4.7",
    reviewsCount: 412,
    featured: false,
  },
  {
    title: "Fisherman's Camp",
    slug: "fishermans-camp-naivasha",
    description:
      "The legendary lakeside escape on Moi South Lake Road — pitch your own tent under the acacias or rent a rustic banda or self-contained cottage. Hippos graze the shoreline at dusk, the lake is perfect for a kayak or a swim (ask the lifeguard first), and the bar has the best sundowners on the lake. The classic Kenyan weekend.",
    propertyType: "campsite",
    roomType: "entire",
    landmark: "Moi South Lake Road",
    hostName: "Fisherman's Camp",
    hostSince: 1994,
    hostBio: "A Naivasha institution — camping, bandas and cottages on the lake's edge since the 90s.",
    superhost: true,
    pricePerNight: 2500,
    peakPricePerNight: 3000,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.fishermanscampnaivasha.com",
    locationName: "Moi South Lake Road, Naivasha",
    region: "Rift Valley Lakes",
    county: "Nakuru",
    latitude: "-0.748900",
    longitude: "36.351900",
    bedrooms: 2,
    beds: 3,
    bathrooms: "1",
    maxGuests: 6,
    amenities: ["Lake view", "Camping pitch", "Bandas & cottages", "Hot showers", "Bar & restaurant", "Kayaks (extra)", "Bonfire", "Free parking", "Mosquito nets", "Security 24/7"],
    highlights: ["Hippos at dusk", "Camp or cottage", "Weekend favourite from Nairobi"],
    imageUrls: imgs(LAKES[1], TENTS[5], LAKES[4], ROOMS[3], LAKES[0], TENTS[0], LAKES[2], TENTS[4]),
    rating: "4.8",
    reviewsCount: 986,
    featured: false,
  },
  {
    title: "Crayfish Camp",
    slug: "crayfish-camp-naivasha",
    description:
      "Lakeside camping and self-contained rooms on Naivasha's quiet south shore — camp under the trees for about a thousand bob, or take a comfortable room with a view over the water. Game and birdlife wander past, and the lakeside restaurant does fresh fish worth the trip alone.",
    propertyType: "campsite",
    roomType: "entire",
    landmark: "Moi South Lake Road",
    hostName: "Crayfish Camp",
    hostSince: 2005,
    hostBio: "Family-run lakeside camp known for camping, fresh lake fish and calm sunsets.",
    superhost: false,
    pricePerNight: 4900,
    peakPricePerNight: 5800,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Moi South Lake Road, Naivasha",
    region: "Rift Valley Lakes",
    county: "Nakuru",
    latitude: "-0.743300",
    longitude: "36.345500",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Lake view", "Camping pitch", "Hot showers", "Bar & restaurant", "Kayaks (extra)", "Bonfire", "Free parking", "Mosquito nets", "Security 24/7"],
    highlights: ["Lakefront camping", "Fresh lake fish", "Quiet south shore"],
    imageUrls: imgs(LAKES[4], LAKES[6], TENTS[2], ROOMS[6], LAKES[1], TENTS[7], TENTS[0], LAKES[3]),
    rating: "4.6",
    reviewsCount: 233,
    featured: false,
  },
  {
    title: "Lanet Matfam Resort",
    slug: "lanet-matfam-nakuru",
    description:
      "A clean, friendly budget resort just off the Nakuru–Nairobi highway — simple en-suite rooms, a garden restaurant and parking, with Menengai crater and town a short ride away. The sensible overnight for the long drive west.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Off Nakuru–Nairobi Hwy",
    hostName: "Matfam Resorts",
    hostSince: 2014,
    hostBio: "A family-run Nakuru favourite for travellers passing through the Rift Valley.",
    superhost: false,
    pricePerNight: 2500,
    peakPricePerNight: 3200,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Lanet, Nakuru",
    region: "Rift Valley Lakes",
    county: "Nakuru",
    latitude: "-0.288100",
    longitude: "36.126400",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Garden", "Bar & restaurant", "Free parking", "Hot water", "Family friendly", "Security 24/7"],
    highlights: ["Off the Nakuru highway", "Garden restaurant", "Great base for Menengai"],
    imageUrls: imgs(ROOMS[6], BALCONY[0], POOLS[5], ROOMS[9], ROOMS[0], BALCONY[3], ROOMS[7], POOLS[1]),
    rating: "4.5",
    reviewsCount: 156,
    featured: false,
  },
  {
    title: "Mountainview Backpackers",
    slug: "mountainview-backpackers-kisumu",
    description:
      "A chilled backpackers in Kisumu's Mamboleo neighbourhood — budget dorms and simple rooms on a quiet plot with mango trees, fifteen minutes from town and the lakeside. Breakfast available, bikes to borrow, and the friendliest welcome in the lakeside city.",
    propertyType: "backpacker",
    roomType: "private",
    landmark: "Mamboleo · 15 min to town",
    hostName: "Mountainview Backpackers",
    hostSince: 2016,
    hostBio: "Kisumu's budget backpacker spot — garden stays minutes from Lake Victoria.",
    superhost: true,
    pricePerNight: 2000,
    peakPricePerNight: 2600,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Mamboleo, Kisumu",
    region: "Western Kenya",
    county: "Kisumu",
    latitude: "-0.103000",
    longitude: "34.821000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast (extra)", "Wi-Fi", "Garden", "Hot showers", "Bikes to borrow", "Self-catering kitchen", "Mosquito nets", "Security 24/7"],
    highlights: ["Mango-tree garden", "15 min from the lakeside", "Bike hire on site"],
    imageUrls: imgs(ROOMS[0], BALCONY[5], LAKES[5], ROOMS[5], LAKES[1], ROOMS[8], LAKES[0], BALCONY[2]),
    rating: "4.7",
    reviewsCount: 189,
    featured: false,
  },
  {
    title: "Mahindi Comfy Hotel",
    slug: "mahindi-comfy-eldoret",
    description:
      "A no-nonsense budget hotel off Uganda Road in Eldoret — spotless single rooms from about twelve hundred shillings, hot water, and a proper breakfast. This is where you land after the long coach ride from Nairobi and sleep like a log.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Off Uganda Road",
    hostName: "Mahindi Comfy Hotels",
    hostSince: 2013,
    hostBio: "Eldoret's dependable budget stay — clean rooms at honest prices.",
    superhost: false,
    pricePerNight: 1500,
    peakPricePerNight: 2000,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Eldoret (Uganda Rd)",
    region: "Western Kenya",
    county: "Uasin Gishu",
    latitude: "0.513000",
    longitude: "35.271000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Hot water", "Free parking", "Wi-Fi", "Mosquito nets", "Security 24/7"],
    highlights: ["Singles from KES 1,200", "Off Uganda Road", "Hot water, guaranteed"],
    imageUrls: imgs(ROOMS[5], ROOMS[8], BALCONY[2], ROOMS[4], ROOMS[1], BALCONY[4], ROOMS[7], ROOMS[3]),
    rating: "4.4",
    reviewsCount: 121,
    featured: false,
  },
  {
    title: "Rafiki House Nanyuki",
    slug: "rafiki-house-nanyuki",
    description:
      "A warm little lodge at the foot of Mount Kenya — simple garden rooms, a roaring fireplace for cold Nanyuki nights, and home-cooked meals. Ten minutes from town, twenty from the equator sign, and the perfect base for a mountain weekend.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Nanyuki town",
    hostName: "Rafiki House",
    hostSince: 2015,
    hostBio: "A cosy Nanyuki lodge with a big fireplace and even bigger welcome.",
    superhost: true,
    pricePerNight: 2600,
    peakPricePerNight: 3300,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Nanyuki",
    region: "Mount Kenya",
    county: "Laikipia",
    latitude: "0.013000",
    longitude: "37.072000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Garden", "Fireplace", "Bar & restaurant", "Free parking", "Hot water", "Family friendly", "Security 24/7"],
    highlights: ["Fireplace evenings", "Home-cooked meals", "20 min from the equator"],
    imageUrls: imgs(BALCONY[1], ROOMS[3], KILIMANJARO[4], ROOMS[0], ROOMS[8], BALCONY[6], ROOMS[2], KILIMANJARO[2]),
    rating: "4.8",
    reviewsCount: 264,
    featured: false,
  },
  {
    title: "Green Hills Hotel",
    slug: "green-hills-hotel-nyeri",
    description:
      "Nyeri's old-school classic — a proper breakfast, a manicured garden, and clean rooms five minutes from town. Since the 1950s travellers have stopped here on the road up-country; the bar still has stories.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Nyeri town",
    hostName: "Green Hills Hotels",
    hostSince: 1955,
    hostBio: "A Nyeri institution — dependable rooms and legendary breakfasts for over six decades.",
    superhost: false,
    pricePerNight: 3500,
    peakPricePerNight: 4500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Nyeri",
    region: "Mount Kenya",
    county: "Nyeri",
    latitude: "-0.420000",
    longitude: "36.947000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Garden", "Bar & restaurant", "Free parking", "Hot water", "Security 24/7"],
    highlights: ["Since 1955", "Famous breakfasts", "Five minutes from town"],
    imageUrls: imgs(ROOMS[4], BALCONY[7], POOLS[3], ROOMS[6], BALCONY[0], ROOMS[2], ROOMS[9], BALCONY[4]),
    rating: "4.6",
    reviewsCount: 501,
    featured: false,
  },
  {
    title: "Thiiri Cultural Centre",
    slug: "thiiri-cultural-centre-meru",
    description:
      "Sleep in a Meru cultural banda at the heart of the community — traditional architecture, honest meals, and hosts who'll teach you a song if you ask. Minutes from Meru town and a world away from it. Every stay supports local crafts and education.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Meru town",
    hostName: "Thiiri Cultural Centre",
    hostSince: 2008,
    hostBio: "A community-run cultural centre with traditional bandas and Meru hospitality.",
    superhost: true,
    pricePerNight: 2000,
    peakPricePerNight: 2500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Meru",
    region: "Mount Kenya",
    county: "Meru",
    latitude: "0.050000",
    longitude: "37.650000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Garden", "Hot water", "Cultural visits", "Nature walks", "Free parking", "Mosquito nets", "Security 24/7"],
    highlights: ["Traditional bandas", "Community-run", "Meru food & song"],
    imageUrls: imgs(ROOMS[7], BALCONY[6], KILIMANJARO[6], ROOMS[3], ROOMS[0], BALCONY[2], ROOMS[5], ROOMS[9]),
    rating: "4.9",
    reviewsCount: 88,
    featured: false,
  },
  {
    title: "Brooklyn Hotel Machakos",
    slug: "brooklyn-hotel-machakos",
    description:
      "A straightforward, spotless budget hotel near Machakos town centre — clean beds, hot water and a filling breakfast, with the free People's Park a short stroll away. The weekend staycation favourite.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Near People's Park",
    hostName: "Brooklyn Hotel",
    hostSince: 2017,
    hostBio: "Machakos town budget stay — clean, central and friendly.",
    superhost: false,
    pricePerNight: 2200,
    peakPricePerNight: 2800,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Machakos town",
    region: "Eastern Kenya",
    county: "Machakos",
    latitude: "-1.517000",
    longitude: "37.267000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Hot water", "Free parking", "Family friendly", "Security 24/7"],
    highlights: ["Steps from People's Park", "Clean, central rooms", "Machakos staycation base"],
    imageUrls: imgs(ROOMS[2], BALCONY[4], ROOMS[9], ROOMS[6], ROOMS[1], BALCONY[0], ROOMS[5], BALCONY[7]),
    rating: "4.5",
    reviewsCount: 143,
    featured: false,
  },
  {
    title: "Blue Post Hotel",
    slug: "blue-post-hotel-thika",
    description:
      "The historic Thika hotel above the Chania Falls — watch the waterfalls thunder past your window from the garden terraces. Standard rooms are simple but spotless, and the view is genuinely world-class for the price.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Chania Falls",
    hostName: "Blue Post Hotels",
    hostSince: 1958,
    hostBio: "Thika's storied garden hotel perched above the Chania Falls since 1958.",
    superhost: false,
    pricePerNight: 3000,
    peakPricePerNight: 3800,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: "https://www.bluepost.co.ke",
    locationName: "Thika (Chania Falls)",
    region: "Eastern Kenya",
    county: "Kiambu",
    latitude: "-1.039000",
    longitude: "37.084000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Garden", "Bar & restaurant", "Free parking", "Hot water", "Waterfall view", "Family friendly", "Security 24/7"],
    highlights: ["Waterfalls from the garden", "Since 1958", "Classic Thika stop"],
    imageUrls: imgs(BALCONY[1], ROOMS[6], LAKES[2], ROOMS[8], LAKES[0], ROOMS[0], ROOMS[3], BALCONY[5]),
    rating: "4.6",
    reviewsCount: 374,
    featured: false,
  },
  {
    title: "New Palm Tree Hotel",
    slug: "new-palm-tree-hotel-mombasa",
    description:
      "Right in the heart of Mombasa town, minutes from the ferry and the old town — clean budget rooms, a decent rooftop, and round-the-clock security. Land here for a city break before heading to the north or south coast beaches.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Mombasa CBD",
    hostName: "New Palm Tree Hotel",
    hostSince: 2011,
    hostBio: "Mombasa town budget stay — central, secure and well-run.",
    superhost: false,
    pricePerNight: 2500,
    peakPricePerNight: 3200,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Mombasa town",
    region: "Coast",
    county: "Mombasa",
    latitude: "-4.055000",
    longitude: "39.670000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Hot water", "Rooftop terrace", "Security 24/7", "Free parking"],
    highlights: ["Heart of Mombasa town", "Near the ferry & old town", "24-hour security"],
    imageUrls: imgs(ROOMS[9], BALCONY[2], ROOMS[5], BEACH[3], BEACH[0], ROOMS[1], ROOMS[7], BALCONY[0]),
    rating: "4.3",
    reviewsCount: 217,
    featured: false,
  },
  {
    title: "Backpacker's Club Malindi",
    slug: "backpackers-club-malindi",
    description:
      "Malindi's meeting point for travellers on a budget — simple rooms and dorms a short walk from town and the beach, a bar that comes alive at sunset, and staff who'll sort your dhow trip, safari or bus ticket. The coast's friendliest cheap bed.",
    propertyType: "backpacker",
    roomType: "private",
    landmark: "Walk to Malindi beach",
    hostName: "Backpacker's Club",
    hostSince: 2009,
    hostBio: "Malindi's classic backpacker stop — dhow trips, beach walks and cold Tusker.",
    superhost: true,
    pricePerNight: 2800,
    peakPricePerNight: 3500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Malindi",
    region: "Coast",
    county: "Kilifi",
    latitude: "-3.216000",
    longitude: "40.117000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Bar & restaurant", "Hot showers", "Travel desk", "Beach access", "Dhow trips (extra)", "Mosquito nets", "Security 24/7"],
    highlights: ["Steps from Malindi beach", "Sunset bar", "Dhow trips arranged"],
    imageUrls: imgs(BEACH[7], ROOMS[1], BEACH[3], SWAHILI[2], BEACH[0], ROOMS[4], ROOMS[9], BALCONY[5]),
    rating: "4.7",
    reviewsCount: 302,
    featured: false,
  },
  {
    title: "Golf Hotel Kakamega",
    slug: "golf-hotel-kakamega",
    description:
      "The classic Kakamega town hotel — a proper breakfast, a garden bar and clean rooms in the heart of the county town, ten minutes from the entrance to Kakamega Forest, the last remnant of the great Guineo-Congolian rainforest. The perfect base for forest walks, birding and the local markets.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Kakamega town · 10 min to the forest",
    hostName: "Golf Hotel Kakamega",
    hostSince: 1958,
    hostBio: "Kakamega's storied town hotel — golfers, forest walkers and county government regulars since the 50s.",
    superhost: false,
    pricePerNight: 3500,
    peakPricePerNight: 4500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Kakamega town",
    region: "Western Kenya",
    county: "Kakamega",
    latitude: "0.283300",
    longitude: "34.752500",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Garden", "Bar & restaurant", "Free parking", "Hot water", "Family friendly", "Security 24/7"],
    highlights: ["Gateway to Kakamega Forest", "Classic town hotel", "Big Sunday buffet"],
    imageUrls: imgs(ROOMS[4], BALCONY[7], ROOMS[6], ROOMS[0], BALCONY[1], ROOMS[2], ROOMS[3], BALCONY[4]),
    rating: "4.5",
    reviewsCount: 276,
    featured: false,
  },
  {
    title: "Pazuri Hotel Kitale",
    slug: "pazuri-hotel-kitale",
    description:
      "A friendly, spotless hotel on the edge of Kitale town — the springboard for Saiwa Swamp National Park, Mt Elgon and the Cherangani Hills. Clean en-suite rooms, a decent restaurant and secure parking, with the famous Kitale museum a short walk away.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Kitale town centre",
    hostName: "Pazuri Hotel",
    hostSince: 2015,
    hostBio: "Kitale's dependable mid-road stay — clean rooms and a kitchen that does proper local food.",
    superhost: false,
    pricePerNight: 2800,
    peakPricePerNight: 3600,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Kitale",
    region: "Western Kenya",
    county: "Trans Nzoia",
    latitude: "1.015700",
    longitude: "35.006200",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Bar & restaurant", "Free parking", "Hot water", "Garden", "Family friendly", "Security 24/7"],
    highlights: ["Springboard for Mt Elgon", "Minutes to Saiwa Swamp NP", "Clean rooms, honest price"],
    imageUrls: imgs(ROOMS[6], BALCONY[2], ROOMS[1], ROOMS[8], ROOMS[0], BALCONY[5], ROOMS[4], ROOMS[3]),
    rating: "4.6",
    reviewsCount: 164,
    featured: false,
  },
  {
    title: "Palm Oasis Resort",
    slug: "palm-oasis-resort-garissa",
    description:
      "Garissa's dependable riverfront address on the banks of the Tana — clean rooms, a leafy compound and a kitchen serving Swahili-Somali dishes you won't find elsewhere in the country. Secure parking and a warm welcome for travellers on the long road east.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Garissa town · Tana River",
    hostName: "Palm Oasis Resort",
    hostSince: 2012,
    hostBio: "A well-run Garissa guesthouse by the Tana — known for its food and secure compound.",
    superhost: false,
    pricePerNight: 4500,
    peakPricePerNight: 5500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Garissa town",
    region: "North Eastern Kenya",
    county: "Garissa",
    latitude: "-0.453600",
    longitude: "39.646100",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Bar & restaurant", "Free parking", "Hot water", "Garden", "Family friendly", "Security 24/7"],
    highlights: ["Tana Riverfront compound", "Swahili-Somali kitchen", "Secure parking on the long road east"],
    imageUrls: imgs(ROOMS[2], BALCONY[4], ROOMS[5], ROOMS[9], ROOMS[1], BALCONY[6], ROOMS[8], BALCONY[3]),
    rating: "4.4",
    reviewsCount: 98,
    featured: false,
  },
  {
    title: "JamboHouse Lamu",
    slug: "jambohouse-lamu",
    description:
      "A relaxed Swahili house in the heart of Lamu Old Town — carved doors, rooftop sea views over the dhow harbour, and simple dorms and private rooms around a plant-filled courtyard. Breakfast on the roof as the dhows sail out; a barefoot stroll to the museum, fort and the seafront.",
    propertyType: "backpacker",
    roomType: "private",
    landmark: "Lamu Old Town · seafront",
    hostName: "JamboHouse Lamu",
    hostSince: 2014,
    hostBio: "A family-run Old Town guesthouse famous for its rooftop breakfasts and dhow-harbour views.",
    superhost: true,
    pricePerNight: 3500,
    peakPricePerNight: 4500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Lamu Old Town",
    region: "Coast",
    county: "Lamu",
    latitude: "-2.271700",
    longitude: "40.902000",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 3,
    amenities: ["Breakfast included", "Wi-Fi", "Rooftop terrace", "Hot showers", "Self-catering kitchen", "Cultural visits", "Dhow trips (extra)", "Mosquito nets", "Sea view"],
    highlights: ["Rooftop over the dhow harbour", "Old Town heritage house", "Dorms & private rooms"],
    imageUrls: imgs(SWAHILI[2], BALCONY[5], SWAHILI[1], ROOMS[7], SWAHILI[0], BEACH[5], BEACH[7], ROOMS[3]),
    rating: "4.8",
    reviewsCount: 214,
    featured: false,
  },
  {
    title: "Distant Relatives",
    slug: "distant-relatives-kilifi",
    description:
      "Kilifi's legendary eco-lodge at the mouth of the creek — dorms from about eighteen hundred shillings, private bandas above the mangroves, and the famous Sunday life-performance nights. Treehouse rooms, a farm-to-table kitchen, kayaks to the ruins, and the friendliest traveller community on the coast.",
    propertyType: "eco_camp",
    roomType: "private",
    landmark: "Kilifi creek · Bofa",
    hostName: "Distant Relatives",
    hostSince: 2012,
    hostBio: "An award-winning eco-lodge and cultural space on the Kilifi creek — dorms, bandas and treehouses.",
    superhost: true,
    pricePerNight: 4500,
    peakPricePerNight: 5500,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    website: "https://www.distantrelatives.co",
    locationName: "Bofa, Kilifi",
    region: "Coast",
    county: "Kilifi",
    latitude: "-3.630500",
    longitude: "39.849900",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast (extra)", "Wi-Fi", "Bar & restaurant", "Kayaks (extra)", "Hammocks", "Eco-friendly", "Dorms available", "Mangrove views", "Music nights", "Hot showers"],
    highlights: ["Dorms from KES 1,800", "Creek-side treehouses", "Legendary Sunday music nights"],
    imageUrls: imgs(ROOMS[3], BALCONY[1], LAKES[4], ROOMS[0], BEACH[1], TENTS[4], TENTS[6], BEACH[6]),
    rating: "4.7",
    reviewsCount: 388,
    featured: false,
  },
  {
    title: "Esstana Guest House",
    slug: "esstana-guest-house-embu",
    description:
      "A clean, no-drama guesthouse in the heart of Embu town — simple en-suite rooms, hot water and a filling breakfast, minutes from the coffee plantations and the slopes of Mt Kenya. The dependable budget bed for the upper-eastern route.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Embu town centre",
    hostName: "Esstana Guest House",
    hostSince: 2016,
    hostBio: "Embu town budget classic — clean rooms and hot showers at honest prices.",
    superhost: false,
    pricePerNight: 2200,
    peakPricePerNight: 2800,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Embu town",
    region: "Eastern Kenya",
    county: "Embu",
    latitude: "-0.531200",
    longitude: "37.450600",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Hot water", "Free parking", "Family friendly", "Security 24/7"],
    highlights: ["Embu town centre", "Coffee-country base", "Hot water, guaranteed"],
    imageUrls: imgs(ROOMS[9], ROOMS[3], BALCONY[3], ROOMS[7], ROOMS[2], BALCONY[1], ROOMS[1], BALCONY[6]),
    rating: "4.5",
    reviewsCount: 87,
    featured: false,
  },
  {
    title: "Gerish Hotel",
    slug: "gerish-hotel-embu",
    description:
      "A well-kept Embu hotel a short walk from the town's markets — spacious rooms, a restaurant that serves proper kienyeji, and secure parking. Travellers on the Nairobi–Embu road know it as the reliable stop before the mountain climbs.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Near Embu market",
    hostName: "Gerish Hotel",
    hostSince: 2013,
    hostBio: "Embu's dependable mid-budget hotel — big rooms and kienyeji food done right.",
    superhost: false,
    pricePerNight: 2800,
    peakPricePerNight: 3500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Embu town",
    region: "Eastern Kenya",
    county: "Embu",
    latitude: "-0.536000",
    longitude: "37.455000",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 3,
    amenities: ["Breakfast included", "Wi-Fi", "Bar & restaurant", "Free parking", "Hot water", "Family friendly", "Security 24/7"],
    highlights: ["Walk to the markets", "Kienyeji restaurant", "Secure parking"],
    imageUrls: imgs(ROOMS[7], BALCONY[6], ROOMS[0], ROOMS[5], ROOMS[4], BALCONY[0], ROOMS[3], BALCONY[4]),
    rating: "4.4",
    reviewsCount: 121,
    featured: false,
  },
  {
    title: "Panesic Hotel",
    slug: "panesic-hotel-embu",
    description:
      "Embu's comfiest mid-tier stay — clean, quiet rooms with firm beds, a proper restaurant and friendly staff who remember your name. Great base for the Seven Forks dams, Mwea rice fields and the trekking routes on Mt Kenya's eastern side.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Embu town · Mt Kenya east",
    hostName: "Panesic Hotel",
    hostSince: 2011,
    hostBio: "A welcoming Embu hotel known for quiet rooms and mountain-trek logistics.",
    superhost: true,
    pricePerNight: 3500,
    peakPricePerNight: 4500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Embu town",
    region: "Eastern Kenya",
    county: "Embu",
    latitude: "-0.538000",
    longitude: "37.459000",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Bar & restaurant", "Free parking", "Hot water", "Garden", "Family friendly", "Security 24/7"],
    highlights: ["Mt Kenya eastern base", "Near Seven Forks dams", "Quiet, comfy rooms"],
    imageUrls: imgs(ROOMS[1], BALCONY[0], ROOMS[8], ROOMS[4], ROOMS[6], BALCONY[7], ROOMS[9], BALCONY[2]),
    rating: "4.7",
    reviewsCount: 176,
    featured: false,
  },
  {
    title: "Tea Hotel Kericho",
    slug: "tea-hotel-kericho",
    description:
      "Kericho's famous tea-country landmark, set in sweeping gardens among the biggest tea estates on earth. Cool 5,000-foot air, a proper highlands breakfast, a fireplace lounge for the evenings and tea tours through the plantations. The classic base for the western highlands — and a bargain at local rates.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Kericho town · tea estates",
    hostName: "Tea Hotel Kericho",
    hostSince: 1954,
    hostBio: "A colonial-era landmark in the tea highlands — gardens, fireplaces and highland hospitality since the 50s.",
    superhost: true,
    pricePerNight: 8500,
    peakPricePerNight: 12500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Kericho town",
    region: "Western Kenya",
    county: "Kericho",
    latitude: "-0.368900",
    longitude: "35.286300",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Bar & restaurant", "Free parking", "Hot water", "Garden", "Tea tours (extra)", "Fireplace lounge", "Family friendly", "Security 24/7"],
    highlights: ["Highlands tea-country classic", "Cool 5,000 ft climate", "Gateway to Mau Forest & Lake Victoria"],
    imageUrls: imgs(ROOMS[0], BALCONY[1], LAKES[2], POOLS[4], ROOMS[5], BALCONY[7], WILDLIFE[7], LAKES[5]),
    rating: "4.7",
    reviewsCount: 312,
    featured: false,
  },
  {
    title: "Rangeland Hotel Isiolo",
    slug: "rangeland-hotel-isiolo",
    description:
      "Isiolo's storied stopover where the Nanyuki road meets the road to Marsabit and Moyale — the last reliable bed before the deserts of the north. Simple en-suite rooms, a courtyard restaurant and secure parking for overland rigs. The gateway town for Samburu, Marsabit and everything north of the mountain.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Isiolo town · gateway to the north",
    hostName: "Rangeland Hotel",
    hostSince: 1965,
    hostBio: "Isiolo's landmark hotel — the dependable stopover for every northern route since the 60s.",
    superhost: false,
    pricePerNight: 3500,
    peakPricePerNight: 4500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Isiolo town",
    region: "Mount Kenya",
    county: "Isiolo",
    latitude: "0.354600",
    longitude: "37.582200",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi", "Bar & restaurant", "Free parking", "Hot water", "Garden", "Family friendly", "Security 24/7"],
    highlights: ["Gateway to Samburu, Marsabit & Moyale", "Classic northern stopover", "Secure parking for overland trips"],
    imageUrls: imgs(ROOMS[2], ROOMS[3], BALCONY[0], ROOMS[8], WILDLIFE[5], LAKES[6], ROOMS[9], BALCONY[4]),
    rating: "4.3",
    reviewsCount: 140,
    featured: false,
  },
  {
    title: "Thomson's Falls Lodge",
    slug: "thomsons-falls-lodge",
    description:
      "A classic budget lodge perched right on the rim above Thomson's Falls, where the Ewaso Narok tumbles 74 metres into a misty gorge. Old-school rooms, a dining room with a straight view down the falls, guided gorge walks and superb birding. The famous cheap stop on the Laikipia road.",
    propertyType: "guesthouse",
    roomType: "entire",
    landmark: "Above Thomson's Falls · Nyahururu",
    hostName: "Thomson's Falls Lodge",
    hostSince: 1968,
    hostBio: "Nyahururu's budget classic — the falls view and the gorge walks have drawn travellers for decades.",
    superhost: false,
    pricePerNight: 4000,
    peakPricePerNight: 5500,
    cleaningFee: 0,
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    website: null,
    locationName: "Nyahururu",
    region: "Mount Kenya",
    county: "Nyandarua",
    latitude: "0.035000",
    longitude: "36.366700",
    bedrooms: 1,
    beds: 1,
    bathrooms: "1",
    maxGuests: 2,
    amenities: ["Breakfast included", "Wi-Fi (lobby)", "Bar & restaurant", "Free parking", "Hot water", "Garden", "Guided falls walks", "Family friendly", "Security 24/7"],
    highlights: ["Views straight down the falls", "Budget classic on the Laikipia road", "Birding in the gorge"],
    imageUrls: imgs(LAKES[3], WILDLIFE[3], ROOMS[4], BALCONY[5], LAKES[0], ROOMS[1], WILDLIFE[1], BALCONY[2]),
    rating: "4.4",
    reviewsCount: 228,
    featured: false,
  },
  {
    title: "Watamu Backpackers",
    slug: "watamu-backpackers",
    description:
      "A laid-back beach hostel a two-minute stroll from Watamu's turquoise marine-park lagoon. Simple dorms and private rooms around a palm-shaded garden, turtle-season talks, kayak and snorkel hire, and the friendliest travellers' dinner table on the north coast.",
    propertyType: "backpacker",
    roomType: "private",
    landmark: "Watamu Beach · lagoon",
    hostName: "Watamu Backpackers",
    hostSince: 2012,
    hostBio: "Watamu's beach-side travellers' house — turtles, kayaks and rooftop dinners.",
    superhost: true,
    pricePerNight: 2500,
    peakPricePerNight: 3500,
    cleaningFee: 0,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    website: null,
    locationName: "Watamu",
    region: "Coast",
    county: "Kilifi",
    latitude: "-3.350600",
    longitude: "40.017500",
    bedrooms: 1,
    beds: 2,
    bathrooms: "1",
    maxGuests: 3,
    amenities: ["Breakfast (extra)", "Wi-Fi", "Bar & restaurant", "Kayaks & snorkel hire", "Hammocks", "Dorms available", "Hot showers", "Garden", "Turtle-season talks", "Mosquito nets"],
    highlights: ["Steps from the marine-park lagoon", "Dorms from KES 1,500", "Turtle & snorkel season"],
    imageUrls: imgs(BEACH[0], DIANI[1], BEACH[4], ROOMS[6], BALCONY[6], DIANI[5], BEACH[2], ROOMS[3]),
    rating: "4.6",
    reviewsCount: 96,
    featured: false,
  },
];

// Kenyan reality per property: host WhatsApp line, Stima & Maji honesty,
// negotiated rates (monthly / groups) and airport-transfer pricing.
const KENYA_META: Record<
  string,
  {
    hostPhone: string;
    powerBackup: "generator" | "solar" | "grid";
    waterSource: "borehole" | "municipal" | "treated";
    wifiType: "fibre" | "starlink" | "hotspot" | "none";
    monthlyDiscountPct: number;
    groupDiscountPct: number;
    airportTransferKes: number;
  }
> = {
  // NOTE: host phones use the clearly-fictional 0700 000 1xx block (like 555
  // in the US) so no real person ever receives demo WhatsApp messages.
  "angama-mara": { hostPhone: "+254700000101", powerBackup: "solar", waterSource: "borehole", wifiType: "fibre", monthlyDiscountPct: 10, groupDiscountPct: 0, airportTransferKes: 3500 },
  "governors-camp": { hostPhone: "+254700000102", powerBackup: "generator", waterSource: "borehole", wifiType: "hotspot", monthlyDiscountPct: 15, groupDiscountPct: 0, airportTransferKes: 3500 },
  "entim-camp": { hostPhone: "+254700000103", powerBackup: "solar", waterSource: "borehole", wifiType: "hotspot", monthlyDiscountPct: 15, groupDiscountPct: 0, airportTransferKes: 3500 },
  "amboseli-serena-safari-lodge": { hostPhone: "+254700000104", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 4000 },
  "elephant-bedroom-camp": { hostPhone: "+254700000105", powerBackup: "solar", waterSource: "borehole", wifiType: "fibre", monthlyDiscountPct: 10, groupDiscountPct: 0, airportTransferKes: 4500 },
  "ol-pejeta-bush-camp": { hostPhone: "+254700000106", powerBackup: "solar", waterSource: "borehole", wifiType: "fibre", monthlyDiscountPct: 15, groupDiscountPct: 5, airportTransferKes: 4500 },
  "finch-hattons": { hostPhone: "+254700000107", powerBackup: "generator", waterSource: "borehole", wifiType: "fibre", monthlyDiscountPct: 10, groupDiscountPct: 0, airportTransferKes: 5000 },
  "serena-mountain-lodge": { hostPhone: "+254700000108", powerBackup: "generator", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 4000 },
  "lake-naivasha-sopa-resort": { hostPhone: "+254700000109", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 3500 },
  "giraffe-manor": { hostPhone: "+254700000110", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 10, groupDiscountPct: 0, airportTransferKes: 2500 },
  "kinondo-kwetu": { hostPhone: "+254700000111", powerBackup: "generator", waterSource: "borehole", wifiType: "none", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 2000 },
  "diani-sea-lodge": { hostPhone: "+254700000112", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 2000 },
  "the-sands-at-nomad": { hostPhone: "+254700000113", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 2000 },
  "medina-palms-watamu": { hostPhone: "+254700000114", powerBackup: "generator", waterSource: "borehole", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 2000 },
  "peponi-hotel-lamu": { hostPhone: "+254700000115", powerBackup: "generator", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 15, groupDiscountPct: 5, airportTransferKes: 0 },
  // --- Local town stays (everyday Kenyan travellers) ---
  "milimani-backpackers-nairobi": { hostPhone: "+254700000201", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  "fishermans-camp-naivasha": { hostPhone: "+254700000202", powerBackup: "generator", waterSource: "borehole", wifiType: "hotspot", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 0 },
  "crayfish-camp-naivasha": { hostPhone: "+254700000203", powerBackup: "generator", waterSource: "borehole", wifiType: "hotspot", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 0 },
  "lanet-matfam-nakuru": { hostPhone: "+254700000204", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 0 },
  "mountainview-backpackers-kisumu": { hostPhone: "+254700000205", powerBackup: "generator", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  "mahindi-comfy-eldoret": { hostPhone: "+254700000206", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  "rafiki-house-nanyuki": { hostPhone: "+254700000207", powerBackup: "generator", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  "green-hills-hotel-nyeri": { hostPhone: "+254700000208", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 0 },
  "thiiri-cultural-centre-meru": { hostPhone: "+254700000209", powerBackup: "solar", waterSource: "borehole", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 0 },
  "brooklyn-hotel-machakos": { hostPhone: "+254700000210", powerBackup: "grid", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  "blue-post-hotel-thika": { hostPhone: "+254700000211", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 0 },
  "new-palm-tree-hotel-mombasa": { hostPhone: "+254700000212", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 0 },
  "backpackers-club-malindi": { hostPhone: "+254700000213", powerBackup: "generator", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  // --- The six counties we missed (Kakamega, Kitale, Garissa, Lamu, Kilifi, Embu) ---
  "golf-hotel-kakamega": { hostPhone: "+254700000214", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  "pazuri-hotel-kitale": { hostPhone: "+254700000215", powerBackup: "grid", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 0 },
  "palm-oasis-resort-garissa": { hostPhone: "+254700000216", powerBackup: "generator", waterSource: "borehole", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  "jambohouse-lamu": { hostPhone: "+254700000217", powerBackup: "generator", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 0 },
  "distant-relatives-kilifi": { hostPhone: "+254700000218", powerBackup: "solar", waterSource: "borehole", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 0 },
  "esstana-guest-house-embu": { hostPhone: "+254700000219", powerBackup: "grid", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
  "gerish-hotel-embu": { hostPhone: "+254700000220", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 0 },
  "panesic-hotel-embu": { hostPhone: "+254700000221", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 20, groupDiscountPct: 10, airportTransferKes: 0 },
  // --- Four more counties: Kericho, Isiolo, Nyandarua (Nyahururu) + Watamu (Kilifi) ---
  "tea-hotel-kericho": { hostPhone: "+254700000222", powerBackup: "generator", waterSource: "municipal", wifiType: "fibre", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 0 },
  "rangeland-hotel-isiolo": { hostPhone: "+254700000223", powerBackup: "generator", waterSource: "borehole", wifiType: "hotspot", monthlyDiscountPct: 15, groupDiscountPct: 5, airportTransferKes: 0 },
  "thomsons-falls-lodge": { hostPhone: "+254700000224", powerBackup: "generator", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 15, groupDiscountPct: 10, airportTransferKes: 0 },
  "watamu-backpackers": { hostPhone: "+254700000225", powerBackup: "grid", waterSource: "municipal", wifiType: "hotspot", monthlyDiscountPct: 20, groupDiscountPct: 5, airportTransferKes: 0 },
};

// Derive the price tier from the low-season rate (budget / mid / luxury).
const LISTINGS: SeedListing[] = RAW_LISTINGS.map((l) => ({
  ...l,
  ...(KENYA_META[l.slug!] ?? {}),
  priceTier: tierForPrice(l.pricePerNight ?? 0),
}));

// ---------------------------------------------------------------- REVIEWS
type SeedReview = {
  listingSlug: string;
  guestName: string;
  rating: number;
  comment: string;
  stayedOn: string;
  /** Optional guest-submitted photo — curated Pexels shot for the demo. */
  photo?: string;
};

const REVIEWS: SeedReview[] = [
  // Angama Mara
  { listingSlug: "angama-mara", guestName: "Charlotte P.", rating: 5, comment: "Woke to mist in the escarpment below and elephants crossing the Triangle. The most beautiful room I have ever stayed in — pure theatre.", stayedOn: "August 2026", photo: px(WILDLIFE[8]) },
  { listingSlug: "angama-mara", guestName: "Duncan M.", rating: 5, comment: "Balloon at dawn over the Mara, champagne, then a leopard sighting before breakfast. Flawless in every way.", stayedOn: "July 2026" },
  { listingSlug: "angama-mara", guestName: "Aisha K.", rating: 5, comment: "The staff made our anniversary unforgettable — sundowners on the escarpment edge at sunset. Worth every shilling.", stayedOn: "October 2026" },
  // Governors' Camp
  { listingSlug: "governors-camp", guestName: "Tom R.", rating: 5, comment: "River crossing at our door on day two. Classic canvas camp done properly — bucket showers included!", stayedOn: "July 2026", photo: px(WILDLIFE[5]) },
  { listingSlug: "governors-camp", guestName: "Sofia L.", rating: 4, comment: "Wonderful guiding and a real sense of history. Expect the classic camp experience rather than boutique luxury.", stayedOn: "June 2026" },
  { listingSlug: "governors-camp", guestName: "James W.", rating: 5, comment: "Fifty years of practice shows. Drives were long, cold and brilliant — and the campfire sundowners are magic.", stayedOn: "August 2026" },
  // Entim Camp
  { listingSlug: "entim-camp", guestName: "Priya N.", rating: 5, comment: "Three crossings in two days from the camp's own river position. Intimate, warm and brilliantly located.", stayedOn: "September 2026", photo: px(WILDLIFE[0]) },
  { listingSlug: "entim-camp", guestName: "Hans G.", rating: 5, comment: "Small camp, huge wildlife. House drinks by the fire after a lion hunt played out in front of us.", stayedOn: "July 2026" },
  // Amboseli Serena
  { listingSlug: "amboseli-serena-safari-lodge", guestName: "Emma T.", rating: 4, comment: "Elephants at the waterhole from the pool — and Kilimanjaro pink at dawn. Rooms are classic rather than modern, but the setting is unbeatable.", stayedOn: "January 2026", photo: px(WILDLIFE[4]) },
  { listingSlug: "amboseli-serena-safari-lodge", guestName: "David O.", rating: 5, comment: "Our kids counted 60 elephants in an hour. Friendly staff and a very reasonable rate for a park lodge.", stayedOn: "April 2026" },
  // Elephant Bedroom Camp
  { listingSlug: "elephant-bedroom-camp", guestName: "Natalie F.", rating: 5, comment: "An elephant family walked through camp while we had tea. The Special Five were all ticked by day three.", stayedOn: "August 2026", photo: px(WILDLIFE[7]) },
  { listingSlug: "elephant-bedroom-camp", guestName: "Kwame A.", rating: 5, comment: "The riverbank bedroom tents are pure romance — falling asleep to the Ewaso Ng'iro and waking to giraffe.", stayedOn: "June 2026" },
  // Ol Pejeta Bush Camp
  { listingSlug: "ol-pejeta-bush-camp", guestName: "Grace M.", rating: 5, comment: "Seeing the last northern white rhinos with a ranger was profoundly moving. A stay with real purpose.", stayedOn: "July 2026" },
  { listingSlug: "ol-pejeta-bush-camp", guestName: "Rob H.", rating: 4, comment: "Superb guiding, lovely tents. The night drive was the highlight of our whole trip.", stayedOn: "September 2026" },
  // Finch Hattons
  { listingSlug: "finch-hattons", guestName: "Isabella R.", rating: 5, comment: "Lions drinking at the spring beside the pool — surreal. This is old-school safari glamour at its best.", stayedOn: "August 2026" },
  { listingSlug: "finch-hattons", guestName: "Oliver B.", rating: 5, comment: "The camp's setting on the spring is extraordinary. Service and food were impeccable.", stayedOn: "October 2026" },
  // Serena Mountain Lodge
  { listingSlug: "serena-mountain-lodge", guestName: "Anna D.", rating: 4, comment: "Buffalo at the floodlit waterhole all night — the kids didn't sleep and didn't care. Rustic charm in the cloud forest.", stayedOn: "March 2026" },
  { listingSlug: "serena-mountain-lodge", guestName: "Peter K.", rating: 4, comment: "Great base for climbing Mt Kenya. Rooms are dated but the wildlife viewing is world-class.", stayedOn: "February 2026" },
  // Lake Naivasha Sopa
  { listingSlug: "lake-naivasha-sopa-resort", guestName: "Lucy W.", rating: 4, comment: "Hippos grazing the lawn at dusk — our boat trip to Crescent Island was the trip's highlight.", stayedOn: "May 2026" },
  { listingSlug: "lake-naivasha-sopa-resort", guestName: "Mark S.", rating: 4, comment: "Great value lakeside resort. Gardens are lovely; rooms are perfectly comfortable.", stayedOn: "November 2026" },
  // Giraffe Manor
  { listingSlug: "giraffe-manor", guestName: "Hannah B.", rating: 5, comment: "A giraffe head through the breakfast window. I cried. I simply cannot recommend this place enough.", stayedOn: "July 2026", photo: px(WILDLIFE[9]) },
  { listingSlug: "giraffe-manor", guestName: "Liam O.", rating: 5, comment: "Feeding the Rothschild giraffes at eye level was the single most magical moment of our honeymoon.", stayedOn: "December 2026" },
  { listingSlug: "giraffe-manor", guestName: "Zara H.", rating: 5, comment: "1932 elegance, extraordinary conservation story, and the world's most famous breakfast guests.", stayedOn: "August 2026" },
  // Kinondo Kwetu
  { listingSlug: "kinondo-kwetu", guestName: "Megan C.", rating: 5, comment: "Shoes off for four days. Snorkelling the reef, yoga at dawn, all-inclusive and utterly restful.", stayedOn: "January 2026", photo: px(BEACH[5]) },
  { listingSlug: "kinondo-kwetu", guestName: "Samuel J.", rating: 5, comment: "The best value all-inclusive on the south coast. Beachfront bandas under the palms are pure bliss.", stayedOn: "April 2026" },
  { listingSlug: "kinondo-kwetu", guestName: "Claire D.", rating: 4, comment: "Wonderful beach and food. Go in green season for the best rates and quieter sands.", stayedOn: "June 2026" },
  // Diani Sea Lodge
  { listingSlug: "diani-sea-lodge", guestName: "Brian K.", rating: 4, comment: "Solid all-inclusive classic on the best stretch of Diani sand. Great value for families.", stayedOn: "August 2026", photo: px(BEACH[1]) },
  { listingSlug: "diani-sea-lodge", guestName: "Fatima A.", rating: 4, comment: "Reef snorkelling at low tide straight off the beach. Rooms are dated but spotless.", stayedOn: "February 2026" },
  // The Sands at Nomad
  { listingSlug: "the-sands-at-nomad", guestName: "Jessica M.", rating: 5, comment: "Candlelit dinner with our toes in the sand. The pool at high tide is one of the best on the coast.", stayedOn: "July 2026", photo: px(DIANI[3]) },
  { listingSlug: "the-sands-at-nomad", guestName: "Andre V.", rating: 5, comment: "Effortlessly stylish. The seafront dining and cocktails were the highlight of our Diani week.", stayedOn: "September 2026" },
  // Medina Palms
  { listingSlug: "medina-palms-watamu", guestName: "Sophie L.", rating: 5, comment: "Stunning Swahili architecture, lagoon views, and we watched turtles hatching in November. Unforgettable.", stayedOn: "November 2026", photo: px(POOLS[0]) },
  { listingSlug: "medina-palms-watamu", guestName: "Tom D.", rating: 4, comment: "Beautiful villas and pools. Watamu's reef is a short boat ride and worth every shilling.", stayedOn: "December 2026" },
  // Peponi Hotel
  { listingSlug: "peponi-hotel-lamu", guestName: "Rebecca S.", rating: 5, comment: "Lamu time moves slowly and so does dinner — in the best way. Rooftop sundowners over the dhows.", stayedOn: "January 2026" },
  { listingSlug: "peponi-hotel-lamu", guestName: "Chris P.", rating: 5, comment: "A step back to the dhow era. Shela beach, old town alleys and the most relaxed hotel in Kenya.", stayedOn: "March 2026" },
  // Milimani Backpackers
  { listingSlug: "milimani-backpackers-nairobi", guestName: "Kevin Mwangi", rating: 5, comment: "Best budget bed in Nairobi. Free breakfast, hot showers, and the team sorted my Easy Coach ticket to Kisumu before I'd finished my chai.", stayedOn: "July 2026", photo: px(ROOMS[3]) },
  { listingSlug: "milimani-backpackers-nairobi", guestName: "Amara O.", rating: 4, comment: "Clean, friendly and a quick matatu hop to town. Dorms are simple — bring earplugs for the 6am departures.", stayedOn: "August 2026" },
  // Fisherman's Camp
  { listingSlug: "fishermans-camp-naivasha", guestName: "Daniel Wafula", rating: 5, comment: "Our weekend tradition. Pitched the tent under the acacias, hippos grunting all night, best sundowners on the lake.", stayedOn: "June 2026", photo: px(LAKES[6]) },
  { listingSlug: "fishermans-camp-naivasha", guestName: "Lucy Wanjiru", rating: 5, comment: "The bandas are great value and the ablution blocks are spotless. Kayak at dawn — unforgettable.", stayedOn: "September 2026" },
  // Crayfish Camp
  { listingSlug: "crayfish-camp-naivasha", guestName: "Brian Kamau", rating: 4, comment: "Quiet lakeside camping and the fresh fish is genuinely excellent. Book ahead on public holidays.", stayedOn: "August 2026" },
  // Lanet Matfam
  { listingSlug: "lanet-matfam-nakuru", guestName: "Grace Achieng", rating: 4, comment: "Simple, clean and right off the highway — exactly what you need after the drive from Nairobi.", stayedOn: "July 2026" },
  // Mountainview Backpackers
  { listingSlug: "mountainview-backpackers-kisumu", guestName: "Sarah Njeri", rating: 5, comment: "The friendliest welcome in Kisumu. Mangoes from the garden, bikes to borrow, and 15 minutes to the lakeside.", stayedOn: "May 2026" },
  { listingSlug: "mountainview-backpackers-kisumu", guestName: "Tom Ochieng", rating: 4, comment: "Chilled spot in Mamboleo. Breakfast is small but the company around the fire makes up for it.", stayedOn: "October 2026" },
  // Mahindi Comfy
  { listingSlug: "mahindi-comfy-eldoret", guestName: "Peter Kipchoge", rating: 5, comment: "Clean bed for under two grand and hot water after a 6-hour coach ride? Sold. The breakfast chapati is elite.", stayedOn: "August 2026" },
  // Rafiki House
  { listingSlug: "rafiki-house-nanyuki", guestName: "Jane Muthoni", rating: 5, comment: "Cold Nanyuki night, roaring fireplace, home-cooked stew. Felt like visiting family.", stayedOn: "June 2026" },
  { listingSlug: "rafiki-house-nanyuki", guestName: "Hassan A.", rating: 4, comment: "Lovely lodge vibes at town prices. Ten minutes to the equator sign — perfect mountain weekend base.", stayedOn: "July 2026" },
  // Green Hills
  { listingSlug: "green-hills-hotel-nyeri", guestName: "Amina Yusuf", rating: 4, comment: "Old-school Nyeri classic. The breakfast is a legend and the garden is lovely. Rooms are dated but spotless.", stayedOn: "April 2026" },
  // Thiiri
  { listingSlug: "thiiri-cultural-centre-meru", guestName: "Wanjiku N.", rating: 5, comment: "Slept in a traditional banda and ate the best Meru food of my life. They even taught us a song.", stayedOn: "September 2026" },
  // Brooklyn
  { listingSlug: "brooklyn-hotel-machakos", guestName: "Michael Otieno", rating: 4, comment: "Straightforward, clean and near the People's Park. Machakos weekend sorted for less than three grand.", stayedOn: "August 2026" },
  // Blue Post
  { listingSlug: "blue-post-hotel-thika", guestName: "Faith M.", rating: 5, comment: "The waterfall views from the garden are unreal at this price. Standard rooms are basic but spotless.", stayedOn: "July 2026" },
  { listingSlug: "blue-post-hotel-thika", guestName: "David Otieno", rating: 4, comment: "A classic stop. Grab a table by the falls rail, order the fish, and watch the water.", stayedOn: "June 2026" },
  // New Palm Tree
  { listingSlug: "new-palm-tree-hotel-mombasa", guestName: "Ruth Kiprotich", rating: 4, comment: "Central, cheap and secure — the perfect Mombasa town base before the beach. Rooftop is a bonus.", stayedOn: "February 2026" },
  // Backpacker's Club
  { listingSlug: "backpackers-club-malindi", guestName: "Sandra M.", rating: 5, comment: "Met half my next itinerary at the sunset bar. Dhow trip sorted by the staff, beach a short walk away.", stayedOn: "January 2026" },
  { listingSlug: "backpackers-club-malindi", guestName: "Kevin Mwangi", rating: 4, comment: "Malindi's budget classic — simple rooms, great people, unbeatable price near the beach.", stayedOn: "December 2026" },
  // Golf Hotel Kakamega
  { listingSlug: "golf-hotel-kakamega", guestName: "Esther Nabwire", rating: 5, comment: "The Sunday buffet is a county institution. Clean room, and the forest entrance is a ten-minute boda ride — we saw colobus monkeys on the walk.", stayedOn: "August 2026", photo: px(BALCONY[3]) },
  { listingSlug: "golf-hotel-kakamega", guestName: "George Barasa", rating: 4, comment: "Old-school Kakamega charm. Rooms are dated but spotless, staff are warm, and you can't beat the location.", stayedOn: "June 2026" },
  // Pazuri Kitale
  { listingSlug: "pazuri-hotel-kitale", guestName: "Brenda Chebet", rating: 5, comment: "Base camp for our Saiwa Swamp trip — clean, quiet and the staff organised our matatu to the park gate. The ugali beef was elite.", stayedOn: "July 2026" },
  // Palm Oasis Garissa
  { listingSlug: "palm-oasis-resort-garissa", guestName: "Ahmed Hassan", rating: 4, comment: "The best food on the Garissa road — the fish and bariis is worth the stop alone. Secure compound, friendly staff.", stayedOn: "September 2026" },
  // JamboHouse Lamu
  { listingSlug: "jambohouse-lamu", guestName: "Nadia Omar", rating: 5, comment: "Breakfast on the roof watching the dhows leave the harbour — worth every shilling. The courtyard is a calm pocket in the Old Town bustle.", stayedOn: "January 2026", photo: px(BEACH[2]) },
  { listingSlug: "jambohouse-lamu", guestName: "Felix Gitau", rating: 5, comment: "Travelled overland from Nairobi on the SGR and ferry — JamboHouse sorted our dhow trip and made Lamu feel easy. Rooftop sunsets are unreal.", stayedOn: "December 2026" },
  // Distant Relatives
  { listingSlug: "distant-relatives-kilifi", guestName: "Winnie Achieng", rating: 5, comment: "Dorm bed for under two grand above the creek. Kayaked to the Mnarani ruins, and the Sunday music night was the best night of our coast trip.", stayedOn: "August 2026", photo: px(BEACH[4]) },
  { listingSlug: "distant-relatives-kilifi", guestName: "Sam Kilonzo", rating: 4, comment: "Treehouse room with mangroves below. Shared bathrooms but spotless, and the farm kitchen does great food. Arrive early for a creek-view hammock.", stayedOn: "July 2026" },
  // Embu trio
  { listingSlug: "esstana-guest-house-embu", guestName: "Mercy Wambui", rating: 4, comment: "Exactly what you need on the Embu road — clean bed, hot shower, hot breakfast. No frills, no surprises.", stayedOn: "May 2026" },
  { listingSlug: "gerish-hotel-embu", guestName: "Joseph Njue", rating: 4, comment: "Kienyeji lunch was superb and the room was spacious. Two minutes from the market — perfect for a coffee-country stop.", stayedOn: "June 2026" },
  { listingSlug: "panesic-hotel-embu", guestName: "Diana Mugure", rating: 5, comment: "Quietest room I've had on the eastern route. Staff remembered my name and sorted an early breakfast before my Mt Kenya trek. Highly recommend.", stayedOn: "September 2026", photo: px(ROOMS[2]) },
  // Tea Hotel Kericho
  { listingSlug: "tea-hotel-kericho", guestName: "Grace Rotich", rating: 5, comment: "A step back in time with proper service. The gardens are stunning and the tea tour was worth every shilling. Cool nights, hot showers, and the breakfast is a feast.", stayedOn: "September 2026" },
  { listingSlug: "tea-hotel-kericho", guestName: "James Kemboi", rating: 4, comment: "Old-school charm in the highlands. Generous breakfast and the staff sorted our matatu connection to Kisumu without fuss.", stayedOn: "June 2026" },
  // Rangeland Hotel Isiolo
  { listingSlug: "rangeland-hotel-isiolo", guestName: "Halima Noor", rating: 4, comment: "Perfect stopover before Marsabit. Clean room, secure parking, and the staff knew every overland route north.", stayedOn: "August 2026" },
  { listingSlug: "rangeland-hotel-isiolo", guestName: "David Ekai", rating: 4, comment: "Classic Isiolo — simple, honest and the food was good. Book early, it fills with northern travellers.", stayedOn: "May 2026" },
  // Thomson's Falls Lodge
  { listingSlug: "thomsons-falls-lodge", guestName: "Carol Wanjiku", rating: 5, comment: "Woke up to the roar of the falls — the view from the dining room is unbeatable for this price. Do the gorge walk at dawn.", stayedOn: "July 2026", photo: px(LAKES[3]) },
  { listingSlug: "thomsons-falls-lodge", guestName: "Peter Miano", rating: 4, comment: "Budget classic done right. Rooms are dated but spotless, and the falls are two minutes away.", stayedOn: "April 2026" },
  // Watamu Backpackers
  { listingSlug: "watamu-backpackers", guestName: "Zainab Ali", rating: 5, comment: "Best value on the coast. Two minutes to the lagoon, turtles in season, and the rooftop dinners are legendary.", stayedOn: "August 2026", photo: px(BEACH[0]) },
  { listingSlug: "watamu-backpackers", guestName: "Tom Odhiambo", rating: 4, comment: "Simple rooms, great people, and they sorted our snorkelling trip to the marine park the same morning.", stayedOn: "July 2026" },
];

// ---------------------------------------------------------------- BOOKINGS
// Deterministic PRNG so reseeding produces the same availability picture.
function mulberry32(seed: number) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const iso = (d: Date) => d.toISOString().slice(0, 10);
const addDays = (base: Date, days: number) => {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d;
};

const GUESTS: [string, string, string][] = [
  ["Jane Muthoni", "jane.muthoni@gmail.com", "+254711100001"],
  ["Peter Kipchoge", "peter.kipchoge@gmail.com", "+254711100002"],
  ["Amina Yusuf", "amina.yusuf@gmail.com", "+254711100003"],
  ["Daniel Wafula", "daniel.wafula@gmail.com", "+254711100004"],
  ["Lucy Wanjiru", "lucy.wanjiru@gmail.com", "+254711100005"],
  ["Michael Otieno", "michael.otieno@gmail.com", "+254711100006"],
  ["Sarah Njeri", "sarah.njeri@gmail.com", "+254711100007"],
  ["Brian Kamau", "brian.kamau@gmail.com", "+254711100008"],
  ["Grace Achieng", "grace.achieng@gmail.com", "+254711100009"],
  ["Kevin Mwangi", "kevin.mwangi@gmail.com", "+254711100010"],
];

type SeedBooking = typeof bookings.$inferInsert;

function generateBookings(idBySlug: Map<string, number>, rates: Map<string, { price: number; cleaning: number; maxGuests: number }>): SeedBooking[] {
  const out: SeedBooking[] = [];
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  for (const [slug, listingId] of idBySlug) {
    const rnd = mulberry32(2000 + listingId);
    const rate = rates.get(slug)!;
    const make = (checkIn: Date, nights: number, past: boolean) => {
      const checkOut = addDays(checkIn, nights);
      const guest = GUESTS[Math.floor(rnd() * GUESTS.length)];
      const guests = 2 + Math.floor(rnd() * Math.max(1, rate.maxGuests - 1));
      return {
        listingId,
        guestName: guest[0],
        guestEmail: guest[1],
        guestPhone: guest[2],
        guestVerified: rnd() > 0.3,
        checkIn: iso(checkIn),
        checkOut: iso(checkOut),
        guests,
        nights,
        totalKes: rate.price * nights + rate.cleaning,
        paymentMethod: rnd() > 0.35 ? "mpesa" : "property",
        status: past ? "completed" : "confirmed",
      };
    };

    // Recent stays → "booked this week/month" stats
    const pastCount = 5 + Math.floor(rnd() * 5);
    for (let i = 0; i < pastCount; i++) {
      const daysAgo = 1 + Math.floor(rnd() * 60);
      out.push(make(addDays(today, -daysAgo), 2 + Math.floor(rnd() * 4), true));
    }

    // Future stays → availability (unavailable dates)
    const futureCount = 5 + Math.floor(rnd() * 5);
    for (let i = 0; i < futureCount; i++) {
      const daysAhead = 7 + Math.floor(rnd() * 90);
      out.push(make(addDays(today, daysAhead), 2 + Math.floor(rnd() * 5), false));
    }
  }
  return out;
}

// ---------------------------------------------------------------- SEED
async function seed() {
  await db.execute(sql`truncate table listings restart identity cascade`);

  const inserted = await db.insert(listings).values(LISTINGS).returning({ id: listings.id, slug: listings.slug });
  const idBySlug = new Map(inserted.map((r) => [r.slug, r.id]));
  const rates = new Map(
    LISTINGS.map((l) => [
      l.slug!,
      { price: l.pricePerNight!, cleaning: l.cleaningFee ?? 0, maxGuests: l.maxGuests ?? 2 },
    ]),
  );

  const reviewRows = REVIEWS.map((r) => ({
    listingId: idBySlug.get(r.listingSlug)!,
    guestName: r.guestName,
    photo: r.photo ?? null,
    rating: r.rating,
    comment: r.comment,
    stayedOn: r.stayedOn,
  }));
  await db.insert(reviews).values(reviewRows);

  const bookingRows = generateBookings(idBySlug, rates);
  await db.insert(bookings).values(bookingRows);

  console.log(`Seeded ${inserted.length} listings, ${reviewRows.length} reviews, ${bookingRows.length} bookings.`);
  await db.execute(sql`select 1`);
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
